/**
 * SentenceService - Frases contextuais para cada palavra do ditado.
 * Para palavras sem frase cadastrada, usa templates que inserem a palavra
 * naturalmente em uma frase, sem revelar a grafia.
 */
class SentenceService {
  constructor() {
    this._bank = {
      'abacate': 'Eu coloquei abacate no sanduíche.',
      'abacaxi': 'O abacaxi é uma fruta tropical muito saborosa.',
      'abelha': 'A abelha faz mel dentro da colmeia.',
      'abertura': 'A abertura do evento foi muito bonita.',
      'abobrinha': 'Minha mãe fez um refogado de abobrinha.',
      'abraço': 'Eu dei um abraço no meu amigo.',
      'abundância': 'Na fazenda havia abundância de frutas.',
      'abóbora': 'A abóbora laranja ficou gostosa no purê.',
      'aceleração': 'A aceleração do carro foi rápida.',
      'acerto': 'Ela comemorou cada acerto na prova.',
      'acolhimento': 'O acolhimento dos professores foi muito carinhoso.',
      'aconchego': 'O aconchego do lar nos faz bem.',
      'acordar': 'Eu preciso acordar cedo amanhã.',
      'acrobacia': 'A acrobacia do ginasta impressionou a plateia.',
      'acácia': 'A acácia floresceu na primavera.',
      'adequado': 'Ele usou um vocabulário adequado para a situação.',
      'adivinhação': 'A adivinhação da professora era muito divertida.',
      'adolescente': 'O adolescente começou a estudar para o colégio.',
      'adoro': 'Eu adoro brincar no parque.',
      'adulto': 'O adulto ajudou a criança a atravessar a rua.',
      'aeroporto': 'Chegamos ao aeroporto duas horas antes do voo.',
      'afeto': 'O afeto dos pais é muito importante para os filhos.',
      'afilhado': 'Meu afilhado ganhou um presente no aniversário.',
      'agulha': 'A costureira usou a agulha para costurar o vestido.',
      'ajuda': 'Eu pedi ajuda para resolver o exercício.',
      'alegria': 'A alegria das crianças no recreio é contagiante.',
      'alface': 'A salada tinha alface bem fresquinha.',
      'algoritmo': 'O algoritmo é uma sequência de passos para resolver um problema.',
      'alho': 'O alho deixou o molho muito saboroso.',
      'alimento': 'O alimento saudável nos dá energia.',
      'almirante': 'O almirante comandava a frota de navios.',
      'alpaca': 'A alpaca tem uma lã muito macia.',
      'altitude': 'A altitude da montanha era muito alta.',
      'ameixa': 'A ameixa é uma fruta roxa e adocicada.',
      'amizade': 'A amizade verdadeira dura para sempre.',
      'amor': 'O amor da família nos fortalece.',
      'amplo': 'O parque tem um espaço amplo para brincar.',
      'anaconda': 'A anaconda é uma das maiores cobras do mundo.',
      'andorinha': 'A andorinha voltou no início da primavera.',
      'animação': 'A animação do filme era muito colorida.',
      'anta': 'A anta é o maior mamífero terrestre do Brasil.',
      'antúrio': 'O antúrio vermelho decorou a sala.',
      'aprender': 'É importante aprender algo novo todos os dias.',
      'aquário': 'No aquário, vimos peixes de muitas cores.',
      'aranha': 'A aranha teceu uma teia entre os galhos.',
      'arara': 'A arara azul é um símbolo do Brasil.',
      'arco-íris': 'Depois da chuva apareceu um lindo arco-íris.',
      'areia': 'A areia da praia estava bem quente.',
      'ariranha': 'A ariranha nada com muita habilidade no rio.',
      'armazém': 'O armazém estava cheio de caixas.',
      'armário': 'As roupas ficam guardadas no armário.',
      'arroz': 'O arroz com feijão é o prato favorito dos brasileiros.',
      'artista': 'O artista pintou um quadro muito bonito.',
      'assado': 'O frango assado ficou dourado e delicioso.',
      'assistente': 'A assistente ajudou o médico durante a consulta.',
      'atenção': 'Preste atenção nas instruções do professor.',
      'atleta': 'O atleta treinou muito para a competição.',
      'aurora': 'A aurora apareceu no horizonte antes do sol nascer.',
      'aventura': 'Nós vivemos uma grande aventura na floresta.',
      'avião': 'O avião decolou no horário previsto.',
      'avó': 'Minha avó faz o melhor bolo de chocolate.',
      'avô': 'Meu avô me contou histórias da infância dele.',
      'azedo': 'O limão tem um gosto azedo.',
      'azulejo': 'O azulejo azul decorava a cozinha.',
      'açaí': 'Eu tomei açaí com granola na praia.',
      'açougue': 'Meu pai foi ao açougue comprar carne.',
      'ação': 'Ele praticou uma ação muito generosa.',
      'babosa': 'A babosa é usada para hidratar a pele.',
      'badminton': 'Nós jogamos badminton no parque.',
      'baião': 'O baião é um ritmo musical do nordeste do Brasil.',
      'balão': 'A criança soltou o balão vermelho no ar.',
      'banana': 'A banana é uma fruta rica em potássio.',
      'bandeira': 'A bandeira do Brasil é verde, amarela e azul.',
      'banho': 'Eu tomo banho todos os dias.',
      'barco': 'O barco navegou pelo lago tranquilo.',
      'barriga': 'Minha barriga doeu depois de comer demais.',
      'batata': 'A batata frita ficou crocante e deliciosa.',
      'beija-flor': 'O beija-flor sugou o néctar da flor rapidamente.',
      'berço': 'O bebê dormia tranquilo no berço.',
      'biblioteca': 'Eu fui à biblioteca pegar um livro de aventura.',
      'bicho': 'Que bicho curioso eu encontrei no jardim!',
      'bicicleta': 'Eu aprendi a andar de bicicleta com meu pai.',
      'biscoito': 'Eu comi um biscoito com leite no café da manhã.',
      'blusão': 'Ela vestiu o blusão porque estava frio.',
      'boca': 'Escovamos os dentes para manter a boca limpa.',
      'bola': 'A bola de futebol rolou para o gol.',
      'bolha': 'A criança fazia bolhas de sabão no quintal.',
      'bondade': 'A bondade dela contagia todas as pessoas.',
      'boneca': 'A menina ganhou uma boneca de presente.',
      'borboleta': 'A borboleta pousou na flor do jardim.',
      'borracha': 'Eu apaguei o erro com a borracha.',
      'boto': 'O boto-cor-de-rosa nada nos rios da Amazônia.',
      'brilho': 'O brilho das estrelas iluminou a noite.',
      'brincadeira': 'A brincadeira favorita das crianças é pega-pega.',
      'brinquedo': 'Ela ganhou um brinquedo novo no aniversário.',
      'bromélia': 'A bromélia é uma planta nativa da América do Sul.',
      'bujão': 'Meu pai foi buscar o bujão de gás.',
      'buriti': 'O buriti é uma palmeira típica do cerrado.',
      'búfalo': 'O búfalo é um animal muito forte.',
      'caatinga': 'A caatinga é um bioma exclusivo do Brasil.',
      'cabelo': 'Ela penteou o cabelo antes de sair.',
      'cabra': 'A cabra pastava no campo com seus filhotes.',
      'cacau': 'O cacau é a fruta usada para fazer chocolate.',
      'cachoeira': 'A cachoeira formava uma piscina natural.',
      'cachorro': 'O cachorro latiu quando ouviu um barulho.',
      'caderno': 'Eu escrevi a lição no caderno.',
      'café': 'Meu pai toma café todas as manhãs.',
      'caju': 'O caju é uma fruta típica do nordeste do Brasil.',
      'calculadora': 'Eu usei a calculadora para resolver a conta.',
      'calor': 'O calor do verão é muito intenso.',
      'camelo': 'O camelo atravessa o deserto sem beber água por dias.',
      'caminho': 'Nós seguimos pelo caminho que levava à cachoeira.',
      'caminhoneiro': 'O caminhoneiro dirigiu a noite toda.',
      'caminhão': 'O caminhão carregava frutas para o mercado.',
      'campo': 'As crianças brincaram no campo de futebol.',
      'canguru': 'O canguru carrega o filhote na bolsa da barriga.',
      'canoa': 'Nós remamos na canoa pelo rio.',
      'canção': 'A professora ensinou uma canção nova para a turma.',
      'capivara': 'A capivara é o maior roedor do mundo.',
      'caranguejo': 'O caranguejo andava de lado na areia.',
      'carinho': 'O carinho da mãe faz toda a diferença.',
      'carne': 'A carne foi assada na churrasqueira.',
      'carrinho': 'O menino brincou com o carrinho de controle remoto.',
      'cartão': 'Eu enviei um cartão de aniversário para minha amiga.',
      'castelo': 'No conto de fadas, a princesa morava em um castelo.',
      'catarata': 'As cataratas do Iguaçu são uma das maiores do mundo.',
      'cavalo': 'O cavalo galopou pelo campo aberto.',
      'cenoura': 'O coelho adorava comer cenoura.',
      'cereja': 'A cereja é uma fruta pequena e vermelha.',
      'cerrado': 'O cerrado é o segundo maior bioma do Brasil.',
      'chave': 'Eu perdi a chave da mochila.',
      'chocolate': 'O bolo de chocolate foi o favorito da festa.',
      'chuva': 'A chuva molhou toda a roupa no varal.',
      'cidade': 'A cidade tinha muitos prédios e carros.',
      'cigarra': 'A cigarra cantava sem parar no verão.',
      'circo': 'As crianças adoraram o espetáculo do circo.',
      'ciência': 'A ciência nos ajuda a entender o mundo.',
      'cobra': 'A cobra se escondeu entre as pedras.',
      'coco': 'O coco da Bahia é muito saboroso.',
      'coelho': 'O coelho pulou pelo jardim comendo cenouras.',
      'colega': 'Meu colega me ajudou com a tarefa de matemática.',
      'colher': 'Eu usei a colher para comer a sopa.',
      'computador': 'Eu aprendi a usar o computador na escola.',
      'confiança': 'A confiança entre amigos é muito importante.',
      'conhecimento': 'O conhecimento é a melhor herança que os pais podem deixar.',
      'construção': 'A construção do prédio durou dois anos.',
      'coragem': 'Ela teve coragem de falar em público.',
      'coração': 'O coração bate mais rápido quando corremos.',
      'corrida': 'A corrida começou e todos os atletas saíram juntos.',
      'cotovelo': 'Ele bateu o cotovelo na mesa sem querer.',
      'couve': 'A couve refogada é muito nutritiva.',
      'criança': 'A criança brincou o dia inteiro no parque.',
      'crocodilo': 'O crocodilo ficou parado à beira do rio.',
      'cuidado': 'Tenha cuidado ao atravessar a rua.',
      'cupuaçu': 'O suco de cupuaçu é muito popular na Amazônia.',
      'curiosidade': 'A curiosidade é o primeiro passo do aprendizado.',
      'cérebro': 'O cérebro é o órgão que controla o nosso corpo.',
      'dança': 'A dança da quadrilha é típica das festas juninas.',
      'decisão': 'Tomar uma boa decisão requer calma e reflexão.',
      'dentista': 'Eu fui ao dentista fazer uma revisão.',
      'desafio': 'Aprender a ler foi um grande desafio.',
      'descanso': 'Após o treino, o descanso é essencial.',
      'descoberta': 'A descoberta do Brasil ocorreu em 1500.',
      'desenho': 'Ela fez um lindo desenho de uma casa.',
      'deserto': 'O deserto do Saara é o maior do mundo.',
      'dever': 'Eu fiz o dever de casa antes de brincar.',
      'dicionário': 'Eu procurei o significado da palavra no dicionário.',
      'dinheiro': 'Ela economizou dinheiro para comprar um livro.',
      'dinossauro': 'O dinossauro era um animal pré-histórico gigante.',
      'direito': 'Todo cidadão tem direito à educação.',
      'diversão': 'A festa de aniversário foi muita diversão.',
      'divisão': 'A divisão é uma das quatro operações matemáticas.',
      'doença': 'O médico cuidou da doença com muito empenho.',
      'dourado': 'O peixe dourado vive nos rios da América do Sul.',
      'dragão': 'No conto, o dragão cuspia fogo pelas narinas.',
      'dúvida': 'Levante a mão se tiver alguma dúvida.',
      'educação': 'A educação é a base de uma sociedade justa.',
      'elefante': 'O elefante é o maior animal terrestre do mundo.',
      'emoção': 'A emoção tomou conta da plateia.',
      'empatia': 'A empatia é a capacidade de sentir o que o outro sente.',
      'energia': 'O sol é uma fonte de energia renovável.',
      'escola': 'Eu adoro ir à escola aprender coisas novas.',
      'escorregador': 'As crianças adoram brincar no escorregador.',
      'escova': 'Eu escovo os dentes três vezes por dia.',
      'escrita': 'A escrita foi uma grande invenção da humanidade.',
      'espaço': 'Os astronautas viajam pelo espaço sideral.',
      'espelho': 'Ela se olhou no espelho antes de sair.',
      'esperança': 'A esperança nos mantém fortes nos momentos difíceis.',
      'esporte': 'O esporte é muito bom para a saúde.',
      'esquelete': 'O esqueleto humano tem mais de duzentos ossos.',
      'estação': 'Minha estação favorita é a primavera.',
      'estrada': 'A estrada levava até a fazenda.',
      'estrela': 'A estrela mais próxima da Terra é o Sol.',
      'estudar': 'É importante estudar todos os dias.',
      'evolução': 'A evolução das espécies foi estudada por Darwin.',
      'exercício': 'O exercício físico faz bem à saúde.',
      'exploração': 'A exploração da Amazônia revelou muitas espécies novas.',
      'família': 'A minha família se reuniu no final de semana.',
      'fantasia': 'A criança vestiu a fantasia de super-herói.',
      'farinha': 'A farinha é um ingrediente essencial do bolo.',
      'fazenda': 'Nas férias, fomos visitar a fazenda do meu tio.',
      'feijão': 'O feijão com arroz é o prato típico brasileiro.',
      'felicidade': 'A felicidade está nas pequenas coisas da vida.',
      'ferreiro': 'O ferreiro moldou o ferro com muita habilidade.',
      'festa': 'A festa de aniversário foi muito animada.',
      'figo': 'O figo é uma fruta doce e mole.',
      'filho': 'O filho ajudou a mãe a preparar o jantar.',
      'flor': 'A flor do jardim perfumou toda a casa.',
      'floresta': 'A floresta amazônica é a maior do mundo.',
      'fogão': 'Minha mãe cozinhou no fogão a lenha.',
      'folha': 'A folha caiu da árvore com o vento.',
      'formiga': 'A formiga carregou um grão de arroz até o formigueiro.',
      'força': 'A força da amizade nos ajuda a superar os obstáculos.',
      'fotossíntese': 'A fotossíntese é o processo pelo qual as plantas produzem alimento.',
      'frango': 'O frango assado ficou dourado e crocante.',
      'frase': 'Ela escreveu uma frase bonita no caderno.',
      'fruta': 'Comer fruta todos os dias é muito saudável.',
      'futebol': 'O futebol é o esporte mais popular do Brasil.',
      'futuro': 'O futuro pertence a quem aprende e se dedica.',
      'fábrica': 'A fábrica produzia sapatos para exportar.',
      'galinha': 'A galinha botou um ovo no ninho.',
      'gato': 'O gato dormia na almofada quente.',
      'geladeira': 'O suco estava gelado na geladeira.',
      'generosidade': 'A generosidade dele emocionou todos os presentes.',
      'girafa': 'A girafa usa o pescoço comprido para alcançar as folhas.',
      'girassol': 'O girassol sempre vira a face para o sol.',
      'globo': 'O professor usou o globo para mostrar os continentes.',
      'goiaba': 'A goiaba é rica em vitamina C.',
      'gorila': 'O gorila é o maior primata do mundo.',
      'gratidão': 'A gratidão é um sentimento muito bonito.',
      'gripe': 'Eu fiquei em casa com gripe por três dias.',
      'guitarra': 'Ele aprendeu a tocar guitarra com doze anos.',
      'hambúrguer': 'Nós comemos hambúrguer no lanche da tarde.',
      'harmonia': 'A harmonia entre os colegas deixa a sala mais feliz.',
      'hipopótamo': 'O hipopótamo passa boa parte do dia na água.',
      'história': 'A professora contou uma história muito emocionante.',
      'honestidade': 'A honestidade é uma virtude muito importante.',
      'horizonte': 'O sol se pôs no horizonte ao entardecer.',
      'horta': 'A escola plantou uma horta no pátio.',
      'hospital': 'Meu avô ficou no hospital por alguns dias.',
      'hotel': 'A família ficou hospedada em um hotel perto da praia.',
      'humildade': 'A humildade é uma qualidade de pessoas sábias.',
      'iguana': 'A iguana ficou parada tomando sol na pedra.',
      'ilha': 'A ilha era rodeada de um mar azul-turquesa.',
      'imaginação': 'A imaginação das crianças não tem limites.',
      'infinito': 'O universo é tão grande que parece infinito.',
      'informação': 'A informação correta é muito valiosa.',
      'invenção': 'A invenção do telefone mudou o mundo.',
      'inverno': 'No inverno, as noites ficam mais longas.',
      'ipê': 'O ipê amarelo floresceu na primavera.',
      'irmão': 'Meu irmão me ajudou a montar o brinquedo.',
      'jabuticaba': 'A jabuticaba nasce direto no tronco da árvore.',
      'jacaré': 'O jacaré ficou imóvel à beira do rio.',
      'jardim': 'O jardim da escola estava cheio de flores.',
      'jiboia': 'A jiboia engole suas presas inteiras.',
      'joelho': 'Ele machucou o joelho ao cair da bicicleta.',
      'jogo': 'O jogo de xadrez exige muita concentração.',
      'jornal': 'Meu avô lê o jornal todas as manhãs.',
      'jovem': 'O jovem estudou muito para passar na prova.',
      'justiça': 'A justiça deve ser igual para todos.',
      'júpiter': 'Júpiter é o maior planeta do sistema solar.',
      'lagartixa': 'A lagartixa subiu pela parede rapidamente.',
      'lagoa': 'As crianças pescaram na lagoa da fazenda.',
      'laranja': 'Eu espremi uma laranja para fazer suco.',
      'lealdade': 'A lealdade é uma das melhores qualidades de um amigo.',
      'legume': 'Os legumes são muito importantes para a saúde.',
      'lemure': 'O lêmure tem olhos grandes e saltitantes.',
      'lenha': 'Meu avô usava lenha para acender a lareira.',
      'leopardo': 'O leopardo é um felino muito ágil.',
      'leão': 'O leão é considerado o rei da selva.',
      'liberdade': 'A liberdade é um direito de todos os cidadãos.',
      'livro': 'Eu leio um livro antes de dormir.',
      'lobo': 'O lobo uivou para a lua cheia.',
      'lontra': 'A lontra nada com muita graça no rio.',
      'lua': 'A lua cheia iluminou toda a noite.',
      'lula': 'A lula tem oito tentáculos e dois braços.',
      'luminária': 'A luminária da sala tinha uma luz bem suave.',
      'macaco': 'O macaco pulou de galho em galho na floresta.',
      'macarrão': 'O macarrão ao molho ficou delicioso.',
      'mamão': 'O mamão é uma fruta muito nutritiva.',
      'manga': 'A manga é uma das frutas mais populares do Brasil.',
      'mangueira': 'A mangueira do jardim tinha muitas mangas maduras.',
      'maracujá': 'O suco de maracujá é muito refrescante.',
      'maravilha': 'A natureza é uma maravilha que devemos preservar.',
      'mariposa': 'A mariposa é atraída pela luz à noite.',
      'matemática': 'Eu gosto muito das aulas de matemática.',
      'maçã': 'Eu comi uma maçã vermelha e doce.',
      'medalha': 'Ela ganhou uma medalha de ouro na olimpíada.',
      'medida': 'A medida do quarto é de quatro metros de largura.',
      'melancia': 'A melancia é perfeita para o verão.',
      'melão': 'O melão estava doce e suculento.',
      'memória': 'A memória da infância nos acompanha para sempre.',
      'mergulho': 'Ele fez um mergulho bonito na piscina.',
      'metrô': 'Eu peguei o metrô para ir ao centro da cidade.',
      'minhoca': 'A minhoca ajuda a deixar a terra mais fértil.',
      'missão': 'A missão dos astronautas durou seis meses.',
      'mochila': 'Eu coloquei os livros na mochila antes de sair.',
      'moinho': 'O velho moinho girava com a força do vento.',
      'montanha': 'Nós subimos a montanha pela trilha.',
      'morango': 'O bolo tinha morangos frescos por cima.',
      'mosquito': 'O mosquito transmite doenças como a dengue.',
      'mula': 'A mula carregava a carga pela estrada íngreme.',
      'médico': 'O médico examinou o paciente com cuidado.',
      'músico': 'O músico tocou violão durante a festa.',
      'nascente': 'A água brotava limpa da nascente da montanha.',
      'natureza': 'Precisamos cuidar da natureza para o futuro.',
      'navio': 'O navio atravessou o oceano em duas semanas.',
      'nação': 'Toda nação deve cuidar do bem-estar do seu povo.',
      'nervo': 'O nervo transmite sinais do cérebro para o corpo.',
      'ninho': 'O passarinho construiu um ninho nos galhos da árvore.',
      'nota': 'Eu tirei uma boa nota na prova de ciências.',
      'nuvem': 'Uma nuvem branca passou pelo céu azul.',
      'oceano': 'O oceano Atlântico banha a costa do Brasil.',
      'onça': 'A onça-pintada é o maior felino das Américas.',
      'orgulho': 'Os pais sentiam orgulho do filho ao ver sua formatura.',
      'orquídea': 'A orquídea é uma das flores mais delicadas.',
      'osso': 'O cachorro enterrou o osso no quintal.',
      'ovelha': 'A ovelha produz a lã usada para fazer roupas.',
      'oxigênio': 'O oxigênio é o gás que respiramos.',
      'paciência': 'A paciência é uma virtude muito importante.',
      'paixão': 'Ele tocava violão com muita paixão.',
      'palmeira': 'A palmeira balançava com a brisa do mar.',
      'panda': 'O panda come bambu quase o dia todo.',
      'pantanal': 'O Pantanal é a maior planície alagável do mundo.',
      'papagaio': 'O papagaio aprendeu a dizer bom dia.',
      'parque': 'As crianças adoram brincar no parque.',
      'passarinho': 'Um passarinho cantou bem cedo pela janela.',
      'paz': 'A paz é o maior bem que podemos cultivar.',
      'peixe': 'O peixe nadou rapidamente pelo aquário.',
      'pelicano': 'O pelicano mergulha para pegar peixes.',
      'pera': 'A pera estava doce e suculenta.',
      'perigo': 'Ele avisou sobre o perigo da rua sem sinalização.',
      'perseverança': 'A perseverança nos ajuda a alcançar nossos sonhos.',
      'pesquisa': 'A pesquisa científica avança a cada ano.',
      'piano': 'Ela tocou uma música linda ao piano.',
      'pinguim': 'O pinguim não consegue voar, mas nada muito bem.',
      'piranha': 'A piranha tem dentes muito afiados.',
      'planeta': 'A Terra é o único planeta com vida conhecida.',
      'plantação': 'A plantação de milho cobria toda a fazenda.',
      'plástico': 'Devemos reciclar o plástico para preservar o meio ambiente.',
      'polvo': 'O polvo pode mudar de cor para se camuflar.',
      'pomar': 'O pomar da fazenda tinha laranjeiras e limoeiros.',
      'pomba': 'A pomba branca é símbolo de paz.',
      'ponte': 'A ponte sobre o rio foi inaugurada hoje.',
      'porco': 'O porco se refrescava na lama do chiqueiro.',
      'português': 'A aula de português é a minha favorita.',
      'praia': 'Nós passamos o dia na praia curtindo o sol.',
      'preguiça': 'A preguiça fica pendurada na árvore a maior parte do dia.',
      'pressão': 'A pressão do vento fechou a janela.',
      'primavera': 'Na primavera as flores desabrocham por todo lado.',
      'professor': 'O professor explicou a matéria com muita clareza.',
      'promoção': 'A promoção da loja atraiu muitos clientes.',
      'proteção': 'A proteção da natureza é responsabilidade de todos.',
      'quadra': 'Os alunos jogaram basquete na quadra da escola.',
      'queijo': 'O queijo minas é muito famoso no Brasil.',
      'quilombo': 'O quilombo dos Palmares foi um símbolo de resistência.',
      'rainha': 'A rainha das abelhas é a mais importante da colmeia.',
      'raposa': 'A raposa é um animal esperto e ágil.',
      'recreio': 'As crianças correm e brincam no recreio.',
      'redação': 'Eu escrevi uma redação sobre o meio ambiente.',
      'reflexão': 'A reflexão nos ajuda a tomar melhores decisões.',
      'relâmpago': 'O relâmpago iluminou o céu durante a tempestade.',
      'relógio': 'O relógio marcava três horas da tarde.',
      'reserva': 'A reserva ambiental protege muitas espécies.',
      'respiração': 'A respiração profunda acalma os nervos.',
      'rinoceronte': 'O rinoceronte tem um chifre na ponta do nariz.',
      'rio': 'O rio Amazonas é o maior do mundo em volume de água.',
      'rocha': 'A rocha era enorme e coberta de musgo.',
      'rosa': 'Ela ganhou uma rosa vermelha de presente.',
      'rua': 'As crianças não devem brincar na rua.',
      'sabiá': 'O sabiá cantou na janela ao amanhecer.',
      'saudade': 'Eu sinto muita saudade da minha avó.',
      'savana': 'Na savana africana vivem leões e zebras.',
      'saúde': 'Praticar exercícios é fundamental para a saúde.',
      'seleção': 'A seleção brasileira de futebol é muito famosa.',
      'selva': 'Na selva amazônica há milhares de espécies de animais.',
      'semente': 'A semente germinou e virou uma árvore enorme.',
      'sensação': 'A sensação de mergulhar no mar é incrível.',
      'serra': 'A serra da Mantiqueira é muito bonita no inverno.',
      'serviço': 'O serviço de entrega chegou muito rápido.',
      'siamês': 'O gato siamês tem olhos azuis muito bonitos.',
      'sistema': 'O sistema solar tem oito planetas.',
      'sobrinho': 'Meu sobrinho aprendeu a andar de bicicleta.',
      'sol': 'O sol nasce a leste e se põe a oeste.',
      'solidariedade': 'A solidariedade faz o mundo melhor.',
      'sonho': 'Nunca desista de realizar o seu sonho.',
      'sopa': 'A sopa de legumes aqueceu a noite fria.',
      'surfe': 'Ele pratica surfe desde os dez anos.',
      'surpresa': 'A festa surpresa deixou ela muito emocionada.',
      'sílaba': 'A palavra escola tem três sílabas.',
      'tamanduá': 'O tamanduá usa a língua longa para comer formigas.',
      'tamborim': 'Ele tocou tamborim no bloco de carnaval.',
      'tartaruga': 'A tartaruga marinha nada com muita elegância.',
      'teclado': 'Eu aprendi a digitar no teclado do computador.',
      'tempestade': 'A tempestade derrubou algumas árvores.',
      'tempo': 'O tempo passou rápido durante as férias.',
      'terra': 'A Terra é o terceiro planeta do sistema solar.',
      'tesoura': 'Eu usei a tesoura para recortar o papel.',
      'tigre': 'O tigre é um felino listrado muito veloz.',
      'tigrão': 'O tigre de bengala é um dos maiores felinos.',
      'tomate': 'O tomate é muito usado no molho de macarrão.',
      'tornado': 'O tornado destruiu várias casas da cidade.',
      'trabalho': 'O trabalho em equipe é muito mais eficiente.',
      'trem': 'O trem chegou na estação no horário certo.',
      'tribunal': 'O juiz julgou o caso no tribunal.',
      'troféu': 'Ela ganhou um troféu pela primeira colocação.',
      'trovão': 'O trovão assustou os animais da fazenda.',
      'tubarão': 'O tubarão-branco é o maior peixe predador do mar.',
      'tucano': 'O tucano tem um bico enorme e colorido.',
      'tulipa': 'A tulipa é uma flor muito popular na Holanda.',
      'universo': 'O universo é tão grande que parece infinito.',
      'urso': 'O urso polar vive nas regiões árticas.',
      'uva': 'A uva é usada para fazer suco e vinho.',
      'vacina': 'A vacina protege as crianças de muitas doenças.',
      'vale': 'O vale entre as montanhas era muito verdejante.',
      'ventania': 'A ventania derrubou as folhas das árvores.',
      'verão': 'No verão, a temperatura fica muito alta.',
      'vespa': 'A vespa tem uma picada dolorosa.',
      'viaduto': 'O carro passou por baixo do viaduto da cidade.',
      'viagem': 'A viagem de férias foi inesquecível.',
      'vida': 'A vida é um presente que devemos valorizar.',
      'violeta': 'A violeta é uma flor de cor roxa muito delicada.',
      'violão': 'Ele aprendeu a tocar violão aos dez anos.',
      'vitória': 'A vitória do time animou todos os torcedores.',
      'viveiro': 'O viveiro tinha mudas de muitas plantas diferentes.',
      'vizinho': 'Meu vizinho tem um jardim muito bem cuidado.',
      'vocabulário': 'Ler livros aumenta o nosso vocabulário.',
      'vulcão': 'O vulcão entrou em erupção e cobriu tudo de cinzas.',
      'xadrez': 'O xadrez é um jogo que desenvolve o raciocínio.',
      'xarope': 'O médico receitou xarope para a tosse.',
      'xícara': 'Minha avó tomou chá na xícara preferida dela.',
      'zebra': 'A zebra tem listras pretas e brancas.',
      'zoológico': 'No zoológico eu vi muitos animais de perto.',
      'área': 'A área do quarto é de doze metros quadrados.',
      'átomo': 'O átomo é a menor parte de um elemento químico.',
    };

    // Templates para palavras sem frase cadastrada.
    // Usam a própria palavra na frase — contexto natural, sem soletrar.
    this._templates = [
      w => `Eu vi um ${w} hoje e fiquei surpreso.`,
      w => `Todo mundo conhece o que é ${w}.`,
      w => `Ela falou sobre ${w} na aula.`,
      w => `O professor perguntou: o que é ${w}?`,
      w => `Eu aprendi que ${w} é muito importante.`,
      w => `Na história, apareceu um ${w} muito interessante.`,
      w => `Você sabe o que significa ${w}?`,
    ];
  }

  /**
   * Retorna uma frase contextual para a palavra.
   * @param {string} word
   * @returns {string}
   */
  getSentence(word) {
    const key = word.toLowerCase().trim().replace(/-/g, '-');
    if (this._bank[key]) return this._bank[key];
    // Palavra não cadastrada: usa template com a palavra na frase
    const idx = word.length % this._templates.length;
    return this._templates[idx](word);
  }
}
