/**
 * WordService - Banco de palavras organizado por nível de dificuldade.
 * Fácil:   1948 palavras  (até 3 sílabas, escrita fonética)
 * Médio:   1434 palavras  (3-4 sílabas, alguns acentos/dígrafos)
 * Difícil: 1604 palavras (4-7 sílabas, múltiplos desafios ortográficos)
 */
class WordService {
  constructor() {
    this._banks = {
      facil: [
      'mel', 'sal', 'pai', 'tio', 'tia', 'giz', 'sol', 'lua',
      'dia', 'mar', 'rio', 'pia', 'wok', 'rim', 'top', 'van',
      'rua', 'bar', 'tom', 'MPB', 'pop', 'rap', 'hub', 'paz',
      'ler', 'rir', 'vir', 'xis', 'dez', 'cem', 'mil', 'par',
      'Sul', 'luz', 'cor', 'som', 'dor', 'cru', 'lei', 'mal',
      'hey', 'eai', 'sim', 'cai', 'foz', 'raia', 'juiz', 'flor',
      'raiz', 'hall', 'puff', 'rack', 'spot', 'veia', 'suor', 'saia',
      'body', 'meia', 'joia', 'trem', 'pneu', 'mall', 'funk', 'rock',
      'jazz', 'soul', 'plug', 'sair', 'feio', 'frio', 'leal', 'real',
      'dois', 'seis', 'maio', 'grau', 'teia', 'caos', 'muar', 'ceia',
      'raio', 'pois', 'psiu', 'mais', 'show', 'cais', 'clips', 'cheia',
      'praia', 'jeans', 'freio', 'rugby', 'blues', 'criar', 'cheio', 'tchau',
      'maior', 'trial', 'shorts', 'street', 'switch', 'brunch', 'tweety', 'ema',
      'ara', 'uva', 'pão', 'ovo', 'chá', 'mãe', 'ano', 'céu',
      'mão', 'ira', 'mês', 'eco', 'vôo', 'pôr', 'têm', 'vêm',
      'jaú', 'véu', 'ali', 'não', 'gás', 'bode', 'vaca', 'galo',
      'pato', 'peru', 'gato', 'leão', 'anta', 'paca', 'tatu', 'lobo',
      'urso', 'boto', 'orca', 'lula', 'sapo', 'caju', 'umbu', 'pera',
      'figo', 'coco', 'kiwi', 'nabo', 'soja', 'bolo', 'sopa', 'doce',
      'suco', 'neto', 'neta', 'nora', 'povo', 'ator', 'gari', 'cola',
      'fita', 'tela', 'mapa', 'lupa', 'tubo', 'sala', 'aula', 'nota',
      'ramo', 'rosa', 'buxo', 'alga', 'limo', 'neve', 'seca', 'halo',
      'mata', 'lago', 'cabo', 'baía', 'atol', 'vale', 'cume', 'pico',
      'duna', 'copa', 'muro', 'teto', 'piso', 'cama', 'mesa', 'foto',
      'vaso', 'cuba', 'rodo', 'pano', 'luva', 'ralo', 'faca', 'copo',
      'bule', 'boca', 'nuca', 'dedo', 'mama', 'coxa', 'pele', 'poro',
      'asma', 'lixa', 'polo', 'maiô', 'capa', 'xale', 'bota', 'anel',
      'mala', 'ouro', 'moto', 'jato', 'bote', 'roda', 'reta', 'vila',
      'loja', 'nado', 'boxe', 'tiro', 'arco', 'remo', 'vela', 'ludo',
      'cubo', 'dado', 'bete', 'lego', 'arpa', 'tuba', 'xote', 'mito',
      'moda', 'fone', 'site', 'jogo', 'riso', 'amor', 'medo', 'nojo',
      'usar', 'belo', 'alto', 'novo', 'seco', 'sujo', 'rico', 'duro',
      'liso', 'chão', 'grão', 'pixe', 'lixo', 'zero', 'três', 'sete',
      'oito', 'nove', 'onze', 'doze', 'nono', 'hora', 'hoje', 'azul',
      'roxo', 'bege', 'oval', 'cone', 'fino', 'reto', 'Acre', 'hino',
      'solo', 'peso', 'gene', 'vida', 'luxo', 'fala', 'mula', 'asno',
      'alce', 'rena', 'mico', 'foca', 'pacu', 'atum', 'dica', 'beca',
      'soma', 'nulo', 'taxa', 'face', 'raso', 'tipo', 'tema', 'rima',
      'auto', 'voto', 'logo', 'caso', 'como', 'fora', 'quem', 'qual',
      'onde', 'viva', 'cana', 'seda', 'siri', 'sobe', 'jaca', 'judo',
      'filo', 'tese', 'peixe', 'cobra', 'cabra', 'touro', 'porco', 'ganso',
      'grilo', 'pombo', 'pomba', 'tigre', 'lince', 'zebra', 'cutia', 'panda',
      'coala', 'polvo', 'ostra', 'coral', 'louro', 'pulga', 'lesma', 'manga',
      'couve', 'aipim', 'torta', 'pizza', 'caldo', 'carne', 'leite', 'creme',
      'pudim', 'cravo', 'cacau', 'primo', 'prima', 'noivo', 'noiva', 'sogro',
      'sogra', 'genro', 'tutor', 'jovem', 'homem', 'gente', 'casal', 'dupla',
      'atriz', 'poeta', 'pasta', 'durex', 'tinta', 'lousa', 'papel', 'livro',
      'atlas', 'globo', 'turma', 'horta', 'texto', 'vogal', 'letra', 'frase',
      'prova', 'teste', 'feira', 'artes', 'caule', 'cacto', 'bambu', 'cedro',
      'mogno', 'pinus', 'murta', 'trufa', 'trevo', 'grama', 'capim', 'junco',
      'taboa', 'chuva', 'brisa', 'vento', 'geada', 'garoa', 'noite', 'tarde',
      'nuvem', 'selva', 'pampa', 'costa', 'lagoa', 'fonte', 'brejo', 'golfo',
      'gruta', 'monta', 'campo', 'haras', 'horto', 'sauna', 'grade', 'porta',
      'banco', 'ducha', 'balde', 'forno', 'forma', 'garfo', 'prato', 'cesto',
      'testa', 'nariz', 'dente', 'ombro', 'pulso', 'palma', 'peito', 'nervo',
      'linfa', 'derme', 'pelos', 'gripe', 'febre', 'raio-x', 'bucha', 'pente',
      'blusa', 'sunga', 'cinto', 'cueca', 'meião', 'touca', 'colar', 'tiara',
      'faixa', 'bolsa', 'prata', 'skate', 'navio', 'barco', 'canoa', 'balsa',
      'bonde', 'barca', 'ferry', 'motor', 'farol', 'viela', 'ponte', 'curva',
      'placa', 'pista', 'posto', 'museu', 'circo', 'clube', 'hotel', 'motel',
      'porto', 'ponto', 'largo', 'golfe', 'surfe', 'salto', 'damas', 'jenga',
      'ritmo', 'clave', 'baixo', 'piano', 'viola', 'cello', 'caixa', 'bumbo',
      'surdo', 'samba', 'baião', 'frevo', 'conto', 'lenda', 'drama', 'magia',
      'filme', 'curta', 'mural', 'mouse', 'modem', 'fibra', 'drone', 'dados',
      'canal', 'calma', 'culpa', 'susto', 'pavor', 'raiva', 'comer', 'beber',
      'mexer', 'picar', 'ralar', 'bater', 'fazer', 'lavar', 'secar', 'jogar',
      'pular', 'nadar', 'falar', 'ouvir', 'notar', 'tocar', 'pagar', 'regar',
      'podar', 'ligar', 'lutar', 'abrir', 'ficar', 'subir', 'parar', 'viver',
      'mudar', 'lindo', 'gordo', 'magro', 'fraco', 'forte', 'atual', 'lento',
      'veloz', 'calmo', 'morno', 'limpo', 'pobre', 'feliz', 'bravo', 'falso',
      'comum', 'cinza', 'macio', 'suave', 'local', 'certo', 'vazio', 'livre',
      'preso', 'solto', 'firme', 'chave', 'chefe', 'xampu', 'xerox', 'expor',
      'choro', 'chute', 'achar', 'achou', 'bicho', 'cacho', 'recho', 'chico',
      'chiba', 'rexer', 'dexar', 'tempo', 'impor', 'bomba', 'bimba', 'rombo',
      'limbo', 'amplo', 'cinco', 'treze', 'vinte', 'sexto', 'dobro', 'ontem',
      'antes', 'nunca', 'sexta', 'abril', 'metro', 'litro', 'verde', 'preto',
      'ciano', 'curto', 'torto', 'Piauí', 'Bahia', 'Goiás', 'Norte', 'Natal',
      'fungo', 'nicho', 'presa', 'ciclo', 'rocha', 'cobre', 'zinco', 'calor',
      'marte', 'clone', 'morte', 'perda', 'poder', 'dever', 'causa', 'gesto',
      'lazer', 'ordem', 'jejum', 'potro', 'veado', 'cervo', 'hiena', 'vison',
      'bugio', 'morsa', 'frito', 'calda', 'pesto', 'salsa', 'festa', 'civil',
      'valsa', 'bloco', 'luzes', 'renas', 'doces', 'fogos', 'resto', 'fator',
      'mista', 'corda', 'setor', 'verbo', 'trama', 'moral', 'crase', 'verso',
      'haiku', 'poema', 'prosa', 'farsa', 'tribo', 'reino', 'polis', 'nobre',
      'servo', 'feudo', 'greve', 'golpe', 'clima', 'bioma', 'reler', 'salvo',
      'enfim', 'perto', 'longe', 'hello', 'claro', 'clipe', 'dedal', 'metal',
      'couro', 'vidro', 'pedra', 'areia', 'trigo', 'pasto', 'pomar', 'solar',
      'truta', 'carpa', 'piaba', 'pargo', 'sargo', 'ficus', 'vedar', 'pesar',
      'medir', 'negar', 'puxar', 'somar', 'menos', 'reduz', 'baixa', 'vezes',
      'dobra', 'menor', 'adeus', 'beijo', 'shiba', 'Zumbi', 'locus', 'leste',
      'oeste', 'delta', 'leito', 'angra', 'gerbil', 'wombat', 'castor', 'lontra',
      'baleia', 'jiboia', 'condor', 'goiaba', 'lichia', 'chuchu', 'pastel', 'frango',
      'geleia', 'picles', 'pintor', 'cantor', 'pincel', 'tablet', 'creche', 'jardim',
      'teatro', 'planta', 'tronco', 'jasmim', 'imbuia', 'freixo', 'musgos', 'fungos',
      'tremor', 'nimbus', 'riacho', 'charco', 'canyon', 'areial', 'rancho', 'closet',
      'chaise', 'buffet', 'painel', 'lustre', 'concha', 'lombar', 'costas', 'plasma',
      'miopia', 'social', 'xadrez', 'blazer', 'poncho', 'brinco', 'casual', 'formal',
      'patins', 'lancha', 'trator', 'airbag', 'diesel', 'hangar', 'aldeia', 'centro',
      'templo', 'squash', 'paddle', 'marcha', 'saltar', 'blocos', 'flauta', 'trompa',
      'reggae', 'poesia', 'design', 'filtro', 'prazer', 'rancor', 'dormir', 'vestir',
      'provar', 'fritar', 'cortar', 'copiar', 'pintar', 'dobrar', 'montar', 'limpar',
      'viajar', 'contar', 'sentir', 'beijar', 'vender', 'trocar', 'teclar', 'cuidar',
      'pensar', 'cantar', 'chorar', 'gritar', 'fechar', 'entrar', 'chegar', 'partir',
      'voltar', 'recuar', 'grande', 'triste', 'gentil', 'doente', 'global', 'frouxo',
      'cheiro', 'chegou', 'xinxim', 'chutar', 'encher', 'rachar', 'brecha', 'flecha',
      'baixar', 'compra', 'sombra', 'bombar', 'tromba', 'trinta', 'triplo', 'depois',
      'sempre', 'kelvin', 'branco', 'prisma', 'Brasil', 'Neymar', 'chumbo', 'feiura',
      'chacal', 'coiote', 'tarsio', 'howler', 'narval', 'cherne', 'vieira', 'hummus',
      'jantar', 'lanche', 'brinde', 'noivos', 'desvio', 'bronze', 'por fim', 'talvez',
      'jamais', 'dentro', 'normal', 'grampo', 'pothos', 'croton', 'zinnia', 'cosmos',
      'soltar', 'largar', 'torcer', 'poupar', 'gastar', 'amplia', 'demais', 'mastim',
      'duatlo', 'Cabral', 'Caxias', 'Rondon', 'meiose', 'bacias', 'fiorde', 'avô',
      'avó', 'ipê', 'axé', 'ímã', 'olá', 'alô', 'hamster', 'mandril',
      'wallaby', 'ketchup', 'catchup', 'coentro', 'recreio', 'stratus', 'freezer', 'shampoo',
      'cropped', 'trailer', 'chimbal', 'virtual', 'podcast', 'pentear', 'cheirar', 'brincar',
      'comprar', 'plantar', 'premiar', 'simples', 'traidor', 'marchar', 'marchou', 'frechar',
      'bombeio', 'cambiar', 'ampliar', 'celsius', 'fractal', 'cristal', 'meerkat', 'recheio',
      'Mundial', 'triplex', 'nuclear', 'proibir', 'triatlo', 'onça', 'maçã', 'açaí',
      'cajá', 'romã', 'alho', 'cará', 'jiló', 'óleo', 'café', 'irmã',
      'bebê', 'cipó', 'maré', 'poço', 'ilha', 'sofá', 'bidê', 'olho',
      'íris', 'unha', 'baço', 'osso', 'boné', 'capô', 'judô', 'oboé',
      'balé', 'robô', 'ódio', 'ágil', 'útil', 'anha', 'caça', 'xodó',
      'área', 'Pará', 'Pelé', 'éden', 'ócio', 'éter', 'aqui', 'além',
      'côco', 'pôde', 'táxi', 'júri', 'ança', 'laço', 'shopping', 'joystick',
      'trimestr', 'contrair', 'subtrair', 'pônei', 'burro', 'arara', 'sabiá', 'iaque',
      'lhama', 'gambá', 'pavão', 'mosca', 'limão', 'mamão', 'amora', 'melão',
      'quivi', 'milho', 'vagem', 'arroz', 'quibe', 'amido', 'molho', 'filho',
      'filha', 'irmão', 'amigo', 'amiga', 'idoso', 'juíza', 'lápis', 'folha',
      'série', 'pátio', 'dança', 'galho', 'lírio', 'tília', 'abeto', 'tufão',
      'verão', 'queda', 'serra', 'morro', 'oásis', 'sítio', 'porão', 'sótão',
      'suíte', 'ferro', 'sabão', 'fogão', 'jarra', 'lábio', 'axila', 'braço',
      'médio', 'dedão', 'unhas', 'saúde', 'tosse', 'otite', 'cárie', 'gesso',
      'exame', 'banho', 'pinça', 'calça', 'lenço', 'sutiã', 'tênis', 'gorro',
      'carro', 'avião', 'balão', 'metrô', 'pisca', 'praça', 'túnel', 'fórum',
      'arena', 'chalé', 'vôlei', 'esqui', 'gamão', 'torre', 'pique', 'álbum',
      'órgão', 'cuíca', 'senha', 'vírus', 'vídeo', 'afeto', 'mágoa', 'fúria',
      'força', 'ciúme', 'assar', 'olhar', 'velho', 'sábio', 'opaco', 'fosco',
      'azedo', 'fácil', 'botão', 'orgão', 'palha', 'bolha', 'rolha', 'falha',
      'telha', 'velha', 'pilha', 'ninho', 'ganho', 'penha', 'vinho', 'linha',
      'tinha', 'vinha', 'cunha', 'punha', 'punho', 'lenha', 'barro', 'terra',
      'garra', 'jarro', 'parra', 'errar', 'passo', 'massa', 'caçar', 'exato',
      'terço', 'ímpar', 'terça', 'março', 'junho', 'julho', 'lilás', 'bordô',
      'Ceará', 'pequi', 'hélio', 'sódio', 'vênus', 'urano', 'sonho', 'risco',
      'âmbar', 'fêmea', 'fólio', 'gêmeo', 'gênio', 'hábil', 'índio', 'látex',
      'móvel', 'níveo', 'sábia', 'porém', 'harém', 'refém', 'algum', 'lança',
      'licão', 'furão', 'sagui', 'gibão', 'glacê', 'razão', 'média', 'faraó',
      'múmia', 'tomão', 'bobão', 'assim', 'então', 'isto é', 'acima', 'atrás',
      'óbvio', 'tricô', 'linho', 'usina', 'solha', 'dália', 'eleva', 'desce',
      'igual', 'akita', 'lhasa', 'barão', 'alelo', 'dique', 'molhe', 'wrestling',
      'construir', 'chantilly', 'coelho', 'cavalo', 'jabuti', 'tucano', 'gavião', 'coruja',
      'girafa', 'gorila', 'macaco', 'camelo', 'alpaca', 'raposa', 'sucuri', 'tritão',
      'barata', 'banana', 'sapoti', 'cereja', 'ameixa', 'pomelo', 'pitaya', 'batata',
      'cebola', 'tomate', 'alface', 'acelga', 'agrião', 'pepino', 'quiabo', 'maxixe',
      'feijão', 'queijo', 'mousse', 'cocada', 'azeite', 'canela', 'marido', 'esposa',
      'colega', 'pupilo', 'menino', 'menina', 'adulto', 'mulher', 'pessoa', 'piloto',
      'garçom', 'editor', 'guarda', 'caneta', 'agenda', 'estojo', 'guache', 'quadro',
      'crachá', 'canudo', 'classe', 'ensino', 'quadra', 'ditado', 'debate', 'visita',
      'troféu', 'inglês', 'avenca', 'tulipa', 'mimosa', 'trovão', 'vulcão', 'cometa',
      'outono', 'aurora', 'cirrus', 'mangue', 'oceano', 'recife', 'abismo', 'colina',
      'parque', 'quarto', 'lavabo', 'sacada', 'portão', 'janela', 'parede', 'lençol',
      'fronha', 'tapete', 'abajur', 'toalha', 'tanque', 'panela', 'colher', 'tigela',
      'caneca', 'cabelo', 'cílios', 'pupila', 'narina', 'palato', 'ouvido', 'queixo',
      'anelar', 'umbigo', 'coluna', 'glúteo', 'joelho', 'pulmão', 'bexiga', 'medula',
      'tendão', 'sangue', 'mucosa', 'córnea', 'retina', 'doença', 'coriza', 'náusea',
      'rinite', 'vacina', 'xarope', 'pomada', 'palito', 'camisa', 'regata', 'pijama',
      'roupão', 'casaco', 'sapato', 'botina', 'chapéu', 'câmbio', 'etanol', 'tarifa',
      'cidade', 'bairro', 'favela', 'bistrô', 'bosque', 'cinema', 'igreja', 'parada',
      'bilhar', 'sinuca', 'kung-fu', 'trilha', 'peteca', 'guerra', 'boneca', 'argila',
      'acorde', 'oitava', 'violão', 'fagote', 'pagode', 'hip-hop', 'bolero', 'carvão',
      'estilo', 'antena', 'tomada', 'terror', 'perdão', 'inveja', 'bocejo', 'sonhar',
      'calçar', 'varrer', 'passar', 'correr', 'narrar', 'adubar', 'operar', 'ajudar',
      'dançar', 'sorrir', 'descer', 'nascer', 'morrer', 'bonito', 'enorme', 'frágil',
      'antigo', 'quente', 'gelado', 'fresco', 'alegre', 'polido', 'rugoso', 'sedoso',
      'amargo', 'aberto', 'paixão', 'flexão', 'cartão', 'dragão', 'melhor', 'brilho',
      'galpão', 'rainha', 'bainha', 'senhor', 'moinho', 'cassar', 'grosso', 'xerife',
      'chorão', 'achado', 'chique', 'mexida', 'abaixo', 'tampão', 'também', 'quatro',
      'quinze', 'quinto', 'oitavo', 'metade', 'minuto', 'semana', 'futuro', 'quarta',
      'quinta', 'agosto', 'volume', 'marrom', 'salmão', 'elipse', 'esfera', 'gaúcho',
      'buriti', 'animal', 'tecido', 'cálcio', 'gasoso', 'atrito', 'empuxo', 'netuno',
      'beleza', 'tolice', 'efeito', 'legado', 'álcool', 'férias', 'grátis', 'júnior',
      'contém', 'nenhum', 'mártir', 'têxtil', 'fértil', 'réptil', 'França', 'caribu',
      'impala', 'texugo', 'glutão', 'lemure', 'galago', 'bonobo', 'mamute', 'robalo',
      'badejo', 'tainha', 'cozido', 'maduro', 'curado', 'capelo', 'pedido', 'viagem',
      'virada', 'oposto', 'altura', 'aresta', 'obtuso', 'tabela', 'evento', 'artigo',
      'enredo', 'clímax', 'ironia', 'soneto', 'novela', 'refrão', 'senado', 'papiro',
      'legião', 'cônsul', 'deriva', 'relevo', 'imoral', 'ilegal', 'dureza', 'rareza',
      'famoso', 'atleta', 'saltão', 'caixão', 'gritão', 'bestão', 'porque', 'embora',
      'apesar', 'quando', 'ou seja', 'a saber', 'de fato', 'tomara', 'por que', 'quanto',
      'bom-dia', 'vedado', 'diário', 'crochê', 'isopor', 'curral', 'popeye', 'traíra',
      'dentão', 'babosa', 'fúcsia', 'afinar', 'avisar', 'atacar', 'alugar', 'cresce',
      'divide', 'bacuri', 'murici', 'sapota', 'Pinzón', 'núcleo', 'mitose', 'genoma',
      'várzea', 'margem', 'medida', 'lagarto', 'morcego', 'pantera', 'lagosta', 'calango',
      'pinguim', 'cacatua', 'formiga', 'besouro', 'caracol', 'laranja', 'pitanga', 'morango',
      'mirtilo', 'toranja', 'atemoia', 'cambuci', 'cenoura', 'bardana', 'pimenta', 'aspargo',
      'palmito', 'bolacha', 'sorvete', 'quindim', 'vinagre', 'tempero', 'alecrim', 'compota',
      'enteado', 'enteada', 'bisneto', 'parente', 'comadre', 'criança', 'soldado', 'padeiro',
      'artista', 'diretor', 'gerente', 'senador', 'militar', 'lixeiro', 'taxista', 'caderno',
      'mochila', 'tesoura', 'furador', 'sulfite', 'revista', 'proveta', 'squeeze', 'cantina',
      'leitura', 'palavra', 'boletim', 'projeto', 'gincana', 'diploma', 'zelador', 'arbusto',
      'pereira', 'videira', 'roseira', 'violeta', 'azaleia', 'lavanda', 'aroeira', 'tornado',
      'ciclone', 'neblina', 'granizo', 'saraiva', 'vazante', 'tsunami', 'estrela', 'planeta',
      'eclipse', 'inverno', 'meio-dia', 'cumulus', 'litoral', 'enseada', 'caverna', 'chapada',
      'encosta', 'outeiro', 'deserto', 'lavoura', 'fazenda', 'viveiro', 'reserva', 'varanda',
      'quintal', 'entrada', 'fachada', 'cortina', 'passeio', 'colchão', 'edredom', 'cadeira',
      'estante', 'retrato', 'capacho', 'avental', 'esponja', 'peneira', 'ralador', 'saleiro',
      'lixeira', 'caixote', 'gengiva', 'maxilar', 'polegar', 'costela', 'quadril', 'cintura',
      'capilar', 'alergia', 'band-aid', 'seringa', 'receita', 'perfume', 'bermuda', 'vestido',
      'moletom', 'echarpe', 'gravata', 'chinelo', 'tamanco', 'viseira', 'pochete', 'bengala',
      'esporte', 'viatura', 'bimotor', 'veleiro', 'jangada', 'fragata', 'guincho', 'volante',
      'bateria', 'estrada', 'rodovia', 'viaduto', 'check-in', 'capital', 'mercado', 'padaria',
      'correio', 'galeria', 'pousada', 'futebol', 'boliche', 'decatlo', 'esgrima', 'hipismo',
      'melodia', 'semitom', 'teclado', 'violino', 'corneta', 'zabumba', 'pintura', 'gravura',
      'mosaico', 'nanquim', 'moldura', 'curador', 'romance', 'musical', 'grafite', 'celular',
      'monitor', 'scanner', 'energia', 'sistema', 'console', 'digital', 'alegria', 'euforia',
      'ternura', 'saudade', 'repulsa', 'espanto', 'bravura', 'bondade', 'empatia', 'timidez',
      'vaidade', 'acordar', 'esticar', 'relaxar', 'meditar', 'maquiar', 'engolir', 'grelhar',
      'refogar', 'estudar', 'colorir', 'ensinar', 'repetir', 'reparar', 'guardar', 'pedalar',
      'passear', 'visitar', 'apertar', 'receber', 'decidir', 'crescer', 'evoluir', 'existir',
      'gigante', 'mediano', 'robusto', 'moderno', 'recente', 'devagar', 'humilde', 'luxuoso',
      'modesto', 'medroso', 'esperto', 'bondoso', 'malvado', 'honesto', 'sincero', 'copiado',
      'salgado', 'picante', 'intenso', 'nervoso', 'cansado', 'exausto', 'popular', 'inteiro',
      'partido', 'repleto', 'fechado', 'fidalgo', 'castelo', 'apontar', 'chegada', 'xistoso',
      'exemplo', 'excluir', 'exercer', 'extremo', 'enchido', 'achismo', 'rachado', 'chicote',
      'mexendo', 'remexer', 'abaixar', 'embaixo', 'empresa', 'emprego', 'impulso', 'imposto',
      'impacto', 'campeão', 'lombada', 'embalar', 'embargo', 'combate', 'limpeza', 'dezoito',
      'setenta', 'oitenta', 'noventa', 'decimal', 'durante', 'domingo', 'feriado', 'janeiro',
      'outubro', 'hectare', 'dourado', 'magenta', 'bicolor', 'losango', 'espiral', 'redondo',
      'pontudo', 'curvado', 'Roraima', 'Alagoas', 'Sergipe', 'Sudeste', 'caipira', 'carioca',
      'tapioca', 'civismo', 'habitat', 'mineral', 'carbono', 'mistura', 'coloide', 'decibel',
      'saturno', 'higiene', 'verdade', 'mentira', 'maldade', 'pobreza', 'direito', 'cultura',
      'vontade', 'jumento', 'carcaju', 'dugongo', 'manatim', 'pintado', 'surubim', 'corvina',
      'garoupa', 'anchova', 'preparo', 'cremoso', 'ganache', 'convite', 'noivado', 'destino',
      'desfile', 'confete', 'coelhos', 'divisor', 'produto', 'parcela', 'numeral', 'ordinal',
      'natural', 'própria', 'convexa', 'reflexo', 'secante', 'mediana', 'sujeito', 'pronome',
      'literal', 'estrofe', 'cantiga', 'tratado', 'governo', 'coliseu', 'tribuno', 'cruzada',
      'reforma', 'senzala', 'nazismo', 'infeliz', 'refazer', 'bipolar', 'bondosa', 'firmeza',
      'nobreza', 'postura', 'lutador', 'ansioso', 'nadador', 'mineiro', 'grandão', 'feiozão',
      'caborge', 'contudo', 'todavia', 'tal qual', 'adiante', 'com quem', 'por quem', 'sem quem',
      'preciso', 'urgente', 'costura', 'bordado', 'madeira', 'granito', 'pocilga', 'cercado',
      'represa', 'cachara', 'lambari', 'dourada', 'maranta', 'dracena', 'adenium', 'tagetes',
      'aceitar', 'aprovar', 'liberar', 'limitar', 'reduzir', 'dilatar', 'alongar', 'alargar',
      'estimar', 'afirmar', 'alertar', 'agredir', 'enrolar', 'separar', 'dividir', 'aumenta',
      'coitado', 'pitomba', 'Colombo', 'Dandara', 'monções', 'garimpo', 'enxofre', 'legenda',
      'baixada', 'geleira', 'iceberg', 'amostra',
      ],
      medio: [
      'ação', 'água', 'égua', 'papagaio', 'leopardo', 'flamingo', 'avestruz', 'graviola',
      'melancia', 'physalis', 'mandioca', 'shiitake', 'manteiga', 'fermento', 'mostarda', 'maionese',
      'gengibre', 'conserva', 'padrasto', 'madrasta', 'familiar', 'parceiro', 'compadre', 'dentista',
      'promotor', 'bombeiro', 'bombeira', 'policial', 'pedreiro', 'vendedor', 'contador', 'cineasta',
      'produtor', 'prefeito', 'vereador', 'ministro', 'cobrador', 'carteiro', 'barbante', 'marcador',
      'projetor', 'semestre', 'bimestre', 'palestra', 'inspetor', 'porteiro', 'ciências', 'biologia',
      'projetos', 'palmeira', 'limoeiro', 'macieira', 'cajueiro', 'mamoeiro', 'cipreste', 'facheiro',
      'vendaval', 'ventania', 'nevoeiro', 'enchente', 'floresta', 'caatinga', 'pantanal', 'restinga',
      'planalto', 'vertente', 'despensa', 'persiana', 'cobertor', 'poltrona', 'floreira', 'pendente',
      'chuveiro', 'torneira', 'chaleira', 'fruteira', 'bochecha', 'garganta', 'peitoral', 'pâncreas',
      'tireoide', 'diarreia', 'consulta', 'cirurgia', 'listrada', 'cachecol', 'pulseira', 'pingente',
      'carteira', 'fantasia', 'triciclo', 'planador', 'cruzeiro', 'lanterna', 'ciclovia', 'pedestre',
      'terminal', 'conjunto', 'hospital', 'pizzaria', 'quiosque', 'tribunal', 'livraria', 'catedral',
      'mosteiro', 'convento', 'handebol', 'beisebol', 'ciclismo', 'pentatlo', 'capoeira', 'harmonia',
      'trompete', 'trombone', 'pandeiro', 'berimbau', 'notebook', 'controle', 'roteador', 'pendrive',
      'internet', 'software', 'programa', 'tristeza', 'surpresa', 'lealdade', 'respeito', 'levantar',
      'repousar', 'respirar', 'mastigar', 'saborear', 'temperar', 'peneirar', 'misturar', 'resolver',
      'calcular', 'recortar', 'inventar', 'aprender', 'explicar', 'produzir', 'fabricar', 'explorar',
      'observar', 'enxergar', 'perceber', 'devolver', 'cultivar', 'desligar', 'instalar', 'cooperar',
      'defender', 'proteger', 'planejar', 'celebrar', 'festejar', 'gracioso', 'atraente', 'chateado',
      'criativo', 'especial', 'vibrante', 'cheiroso', 'disposto', 'nacional', 'regional', 'complexo',
      'completo', 'expandir', 'exterior', 'chocante', 'capricho', 'flechada', 'empolgar', 'importar',
      'impactar', 'cambista', 'trombeta', 'trombose', 'embarcar', 'pombeiro', 'combinar', 'combater',
      'ambiente', 'simpatia', 'duzentos', 'primeiro', 'terceiro', 'presente', 'setembro', 'novembro',
      'dezembro', 'milgrama', 'tricolor', 'diagonal', 'vertical', 'cilindro', 'comprido', 'estreito',
      'Nordeste', 'carnaval', 'feijoada', 'bandeira', 'predador', 'composto', 'circuito', 'condutor',
      'pandemia', 'covardia', 'conforto', 'conflito', 'potranca', 'mangabey', 'marmoset', 'caiarara',
      'siamango', 'lamantim', 'nautilus', 'crocante', 'fervendo', 'grinalda', 'enfeites', 'minuendo',
      'resposta', 'cardinal', 'racional', 'inteiros', 'segmento', 'tangente', 'desfecho', 'dialogal',
      'contexto', 'parlenda', 'medieval', 'Mercosul', 'cantante', 'viajante', 'precioso', 'pianista',
      'portanto', 'conforme', 'concordo', 'opcional', 'proibido', 'restrito', 'cisterna', 'calathea',
      'monstera', 'rejeitar', 'reprovar', 'permitir', 'aumentar', 'diminuir', 'encurtar', 'precisar',
      'garantir', 'declarar', 'anunciar', 'informar', 'advertir', 'afrouxar', 'traduzir', 'decifrar',
      'investir', 'parceria', 'triplica', 'saudades', 'capricha', 'perfeito', 'heptatlo', 'muay-thai',
      'Anchieta', 'Vesputio', 'Palmares', 'entradas', 'simbiose', 'binomial', 'membrana', 'noroeste',
      'sudoeste', 'afluente', 'diagrama', 'bisão', 'águia', 'araçá', 'régua', 'ábaco',
      'ética', 'álamo', 'quipá', 'manhã', 'úvula', 'útero', 'loção', 'agogô',
      'forró', 'ópera', 'úmido', 'árido', 'único', 'nação', 'visão', 'noção',
      'fusão', 'êxito', 'Amapá', 'átomo', 'opção', 'ânimo', 'ácido', 'álula',
      'ático', 'ávido', 'êxodo', 'épico', 'ídolo', 'légua', 'ótimo', 'ícone',
      'cação', 'buquê', 'agudo', 'já que', 'quiçá', 'oxalá', 'acolá', 'aquém',
      'açude', 'centopeia', 'framboesa', 'lancheira', 'trimestre', 'consoante', 'geografia', 'samambaia',
      'goiabeira', 'cachoeira', 'resfriado', 'badminton', 'trampolim', 'taekwondo', 'fantasias', 'reggaeton',
      'conversor', 'nostalgia', 'responder', 'consertar', 'conversar', 'emprestar', 'preservar', 'conservar',
      'priorizar', 'contornar', 'continuar', 'progredir', 'grandioso', 'confiante', 'encharcar', 'caprichar',
      'marchando', 'marchante', 'flecheiro', 'chicotear', 'implantar', 'semblante', 'trombadar', 'ambiental',
      'trezentos', 'anteontem', 'tetraedro', 'Tocantins', 'presentes', 'Halloween', 'gladiador', 'microchip',
      'marcheiro', 'flautista', 'no entanto', 'realmente', 'prendedor', 'boulevard', 'bugs-bunny', 'impatiens',
      'concordar', 'comprimir', 'estreitar', 'confirmar', 'desdobrar', 'converter', 'encriptar', 'financiar',
      'cherimoia', 'iguana', 'ovelha', 'búfalo', 'ouriço', 'jacaré', 'faisão', 'abelha',
      'aranha', 'tâmara', 'rúcula', 'inhame', 'paçoca', 'açúcar', 'bisavô', 'bisavó',
      'médico', 'médica', 'físico', 'músico', 'béquer', 'escola', 'sílaba', 'índice',
      'música', 'física', 'árvore', 'jatobá', 'acácia', 'bétula', 'aragem', 'ilhota',
      'roçado', 'ateliê', 'escada', 'rodapé', 'cômoda', 'escova', 'xícara', 'cabeça',
      'língua', 'orelha', 'mínimo', 'fígado', 'ovário', 'vômito', 'agulha', 'sólida',
      'paletó', 'óculos', 'ônibus', 'câmara', 'hóquei', 'karatê', 'aikidô', 'dominó',
      'canção', 'escala', 'maracá', 'fábula', 'imagem', 'câmera', 'código', 'dúvida',
      'cobiça', 'rápido', 'tépido', 'tímido', 'áspero', 'básico', 'inútil', 'errado',
      'mansão', 'tensão', 'pinhão', 'acolho', 'assado', 'exceto', 'âmbito', 'milhão',
      'bilhão', 'sétimo', 'décimo', 'fração', 'década', 'século', 'sábado', 'índigo',
      'Paraná', 'Páscoa', 'vatapá', 'tucumã', 'escudo', 'brasão', 'célula', 'fóssil',
      'sólido', 'espaço', 'ameaça', 'ântena', 'âncora', 'cássia', 'cônego', 'débito',
      'êxtase', 'élfico', 'ênfase', 'gênero', 'gótico', 'hábito', 'hálito', 'íntimo',
      'lápide', 'lépido', 'lúcido', 'lúpulo', 'mérito', 'método', 'módulo', 'nítido',
      'número', 'óptica', 'órbita', 'pálido', 'rígido', 'súbito', 'títere', 'válido',
      'vívido', 'zênite', 'último', 'alguém', 'míssil', 'amável', 'porção', 'almoço',
      'arraiá', 'dígito', 'máxima', 'coesão', 'figura', 'além de', 'lógico', 'esboço',
      'eólica', 'bagaço', 'olhete', 'de-nada', 'abraço', 'babaçu', 'caratê', 'meação',
      'maciço', 'grapefruit', 'champignon', 'grampeador', 'flamboyant', 'influencer', 'contribuir', 'empreender',
      'subtraendo', 'concluindo', 'restringir', 'pentathlon', 'gatinho', 'canário', 'esquilo', 'galinha',
      'babuíno', 'canguru', 'equidna', 'tubarão', 'camarão', 'axolote', 'cigarra', 'minhoca',
      'abacaxi', 'cupuaçu', 'abacate', 'damasco', 'repolho', 'ervilha', 'coxinha', 'esfirra',
      'iogurte', 'farinha', 'tomilho', 'açafrão', 'cúrcuma', 'cunhado', 'cunhada', 'vizinho',
      'vizinha', 'família', 'biólogo', 'geólogo', 'técnico', 'origami', 'balança', 'garrafa',
      'colégio', 'ginásio', 'escrita', 'sumário', 'reforço', 'medalha', 'amizade', 'antúrio',
      'gérbera', 'begônia', 'plátano', 'líquens', 'nenúfar', 'furacão', 'orvalho', 'ressaca',
      'galáxia', 'miragem', 'cerrado', 'pântano', 'alagado', 'morrote', 'chácara', 'cozinha',
      'garagem', 'estúdio', 'piscina', 'telhado', 'azulejo', 'calçada', 'armário', 'espelho',
      'relógio', 'barriga', 'abdômen', 'cérebro', 'artéria', 'remédio', 'cápsula', 'atadura',
      'algodão', 'macacão', 'jaqueta', 'calçado', 'aliança', 'carreta', 'reboque', 'híbrido',
      'avenida', 'alameda', 'bilhete', 'bagagem', 'horário', 'clínica', 'sacolão', 'estádio',
      'armazém', 'oficina', 'lavagem', 'colônia', 'velório', 'esquina', 'corrida', 'baralho',
      'memória', 'bolinha', 'caçador', 'ukulele', 'desenho', 'colagem', 'crítico', 'crônica',
      'comédia', 'veículo', 'sorriso', 'carinho', 'orgulho', 'vitória', 'solidão', 'coragem',
      'diálogo', 'egoísmo', 'escovar', 'arrumar', 'amassar', 'escalar', 'escutar', 'abraçar',
      'avançar', 'pequeno', 'molhado', 'caótico', 'animado', 'ingênuo', 'educado', 'agitado',
      'inodoro', 'sozinho', 'isolado', 'difícil', 'correto', 'conexão', 'ocasião', 'papelão',
      'cidadão', 'capitão', 'criação', 'amarelo', 'batalha', 'caminho', 'ranhura', 'canhoto',
      'vinhedo', 'senhora', 'espinho', 'chaminé', 'tamanho', 'arranha', 'arrepio', 'arrasto',
      'arranjo', 'socorro', 'terreno', 'assunto', 'assumir', 'assinar', 'assento', 'passivo',
      'massivo', 'cassino', 'acessar', 'límpido', 'segundo', 'milênio', 'passado', 'às vezes',
      'segunda', 'círculo', 'regular', 'espesso', 'Paraíba', 'São-João', 'moqueca', 'ser-vivo',
      'matéria', 'umidade', 'titânio', 'silício', 'argônio', 'inércia', 'júpiter', 'herança',
      'justiça', 'avareza', 'traição', 'mudança', 'sucesso', 'derrota', 'riqueza', 'álgebra',
      'bálsamo', 'cântaro', 'cárpato', 'cítrico', 'cônjuge', 'cômputo', 'dígrafo', 'fábrica',
      'fórmula', 'período', 'pólvora', 'próximo', 'público', 'rústico', 'símbolo', 'síntese',
      'tráfego', 'vértice', 'íntegro', 'ninguém', 'durável', 'visível', 'balanço', 'hortelã',
      'cajuína', 'doninha', 'arminhe', 'muriqui', 'piranha', 'piraíba', 'vôngole', 'molusco',
      'petisco', 'nova-era', 'cálculo', 'décimos', 'largura', 'côncavo', 'gráfico', 'espécie',
      'métrica', 'anedota', 'império', 'tráfico', 'equador', 'trópico', 'amoroso', 'casinha',
      'docinho', 'bezerro', 'dado que', 'a não ser', 'para que', 'que tipo', 'inexato', 'mármore',
      'piquete', 'tilápia', 'gerânio', 'petúnia', 'caninha', 'segurar', 'agarrar', 'por-nada',
      'tadinho', 'dálmata', 'pupunha', 'Nóbrega', 'fósforo', 'domínio', 'vacúolo', 'isobara',
      'esquema', 'transformar', 'compreender', 'transversal', 'cachorro', 'guepardo', 'elefante', 'capivara',
      'tamanduá', 'guaxinim', 'golfinho', 'anaconda', 'cascavel', 'jararaca', 'camaleão', 'pelicano',
      'mariposa', 'mosquito', 'caramujo', 'mexerica', 'brócolis', 'almeirão', 'chicória', 'rabanete',
      'pimentão', 'lentilha', 'biscoito', 'rapadura', 'salsinha', 'baunilha', 'caramelo', 'gelatina',
      'vitamina', 'limonada', 'refresco', 'sobrinho', 'sobrinha', 'namorado', 'namorada', 'padrinho',
      'madrinha', 'advogado', 'advogada', 'ferreiro', 'pescador', 'geógrafo', 'repórter', 'escultor',
      'escritor', 'deputado', 'operador', 'analista', 'borracha', 'compasso', 'esquadro', 'fichário',
      'apagador', 'apostila', 'uniforme', 'mochilão', 'prefácio', 'simulado', 'gabarito', 'pesquisa',
      'trabalho', 'história', 'espanhol', 'religião', 'coqueiro', 'figueira', 'oliveira', 'bromélia',
      'girassol', 'gardênia', 'magnólia', 'pinheiro', 'carvalho', 'nogueira', 'briófita', 'estiagem',
      'nebulosa', 'ribeirão', 'catarata', 'nascente', 'planície', 'montanha', 'pastagem', 'estância',
      'banheiro', 'corredor', 'academia', 'elevador', 'banqueta', 'aparador', 'arandela', 'banheira',
      'secadora', 'vassoura', 'esfregão', 'pálpebra', 'cotovelo', 'próstata', 'cerebelo', 'neurônio',
      'hemácias', 'epiderme', 'sinusite', 'curativo', 'sabonete', 'cotonete', 'camiseta', 'camisola',
      'calcinha', 'sandália', 'mocassim', 'corrente', 'presilha', 'patinete', 'patrulha', 'carrinho',
      'gasolina', 'travessa', 'embarque', 'subúrbio', 'berçário', 'farmácia', 'cartório', 'presídio',
      'boutique', 'magazine', 'albergue', 'mesquita', 'sinagoga', 'terreiro', 'basquete', 'lacrosse',
      'mergulho', 'maratona', 'jiu-jitsu', 'canoagem', 'queimada', 'massinha', 'guitarra', 'acordeão',
      'saxofone', 'chocalho', 'maracatu', 'tragédia', 'logotipo', 'mensagem', 'gratidão', 'abandono',
      'vergonha', 'mal-estar', 'ganância', 'bostejão', 'degustar', 'cozinhar', 'escrever', 'desenhar',
      'melhorar', 'caminhar', 'carregar', 'imaginar', 'aparecer', 'elegante', 'delicado', 'vagaroso',
      'ordenado', 'abastado', 'corajoso', 'inocente', 'duvidoso', 'dedicado', 'inovador', 'original',
      'colorido', 'saudável', 'sociável', 'fictício', 'apertado', 'reflexão', 'vermelho', 'conselho',
      'pastelão', 'ferrinha', 'arrastar', 'terrible', 'passante', 'processo', 'associar', 'discutir',
      'processe', 'executar', 'chorinho', 'bichinho', 'empurrar', 'empalhar', 'campanha', 'pombinha',
      'limpinho', 'quatorze', 'dezenove', 'quarenta', 'sessenta', 'quinzena', 'enquanto', 'tonelada',
      'turquesa', 'paralela', 'quadrado', 'trapézio', 'Amazonas', 'Rondônia', 'quilombo', 'castanha',
      'bactéria', 'ecologia', 'altitude', 'latitude', 'petróleo', 'magnésio', 'elemento', 'isolante',
      'mercúrio', 'universo', 'digestão', 'epidemia', 'contágio', 'pesadelo', 'fracasso', 'prejuízo',
      'vantagem', 'bem-estar', 'fraqueza', 'silêncio', 'descanso', 'natureza', 'barbárie', 'múltiplo',
      'plástico', 'tríplice', 'parabéns', 'flexível', 'bacalhau', 'trem-bala', 'facocero', 'suricata',
      'tamarino', 'peixe-boi', 'arapaima', 'pirarucu', 'matrinxã', 'sardinha', 'xerelete', 'berbigão',
      'mariscos', 'planária', 'refogado', 'grelhado', 'sequinho', 'marinado', 'defumado', 'merengue',
      'docinhos', 'embrulho', 'lua-de-mel', 'fogueira', 'quitutes', 'positivo', 'negativo', 'infinito',
      'absoluto', 'aparente', 'diâmetro', 'paralelo', 'adjetivo', 'advérbio', 'narrador', 'regência',
      'ditadura', 'economia', 'pecuária', 'comércio', 'serviços', 'alfabeto', 'caravela', 'fascismo',
      'generoso', 'corajosa', 'frescura', 'dançante', 'perigoso', 'livrinho', 'florinha', 'calorzão',
      'covardão', 'peixinho', 'pintinho', 'visto que', 'mesmo que', 'ainda que', 'desde que', 'assim que',
      'em resumo', 'de início', 'logo após', 'obrigado', 'obrigada', 'desculpe', 'boa-tarde', 'boa-noite',
      'bem-vindo', 'discordo', 'incrível', 'evidente', 'esperado', 'demorado', 'depressa', 'alfinete',
      'calcário', 'ferrovia', 'biomassa', 'tom-jerry', 'tambaqui', 'pirarara', 'linguado', 'gladíolo',
      'esquivar', 'analisar', 'desconta', 'por-favor', 'boa-sorte', 'vai-fundo', 'manda-ver', 'muito-bem',
      'malamute', 'Dom-Pedro', 'colonato', 'onivoria', 'isoterma', 'isohieta', 'isostata', 'estuário',
      'premissa', 'variável', 'transplantar', 'tartaruga', 'calopsita', 'porquinho', 'beija-flor', 'chimpanzé',
      'crocodilo', 'lagartixa', 'borboleta', 'louva-deus', 'lacrainha', 'carambola', 'tangerina', 'nectarina',
      'grumixama', 'espinafre', 'couve-flor', 'berinjela', 'sanduíche', 'chocolate', 'marmelada', 'champanhe',
      'professor', 'motorista', 'encanador', 'vendedora', 'diplomata', 'vigilante', 'digitador', 'apontador',
      'cartolina', 'intervalo', 'diretoria', 'parquinho', 'monitoria', 'formatura', 'filosofia', 'suculenta',
      'bananeira', 'mangueira', 'ameixeira', 'margarida', 'hortênsia', 'pau-brasil', 'eucalipto', 'salgueiro',
      'podocarpo', 'mandacaru', 'bromélias', 'chuviscar', 'avalanche', 'asteroide', 'solstício', 'primavera',
      'anoitecer', 'madrugada', 'meia-noite', 'horizonte', 'peninsula', 'tabuleiro', 'veneziana', 'gaveteiro',
      'papeleira', 'toalheiro', 'geladeira', 'batedeira', 'cafeteira', 'indicador', 'tornozelo', 'calcanhar',
      'intestino', 'ligamento', 'plaquetas', 'gengivite', 'ultrassom', 'fio-dental', 'estampada', 'sobretudo',
      'salto-alto', 'bracelete', 'sombrinha', 'bijuteria', 'bicicleta', 'ultraleve', 'submarino', 'guindaste',
      'betoneira', 'embreagem', 'travessia', 'aeroporto', 'periferia', 'faculdade', 'delegacia', 'papelaria',
      'atletismo', 'acrobacia', 'brinquedo', 'partitura', 'clarinete', 'triangulo', 'sertanejo', 'sapateado',
      'tendência', 'microfone', 'adaptador', 'navegador', 'algoritmo', 'videogame', 'realidade', 'aumentada',
      'metaverso', 'conquista', 'confiança', 'ansiedade', 'desagrado', 'incerteza', 'compaixão', 'humildade',
      'paciência', 'adormecer', 'descansar', 'descascar', 'perguntar', 'memorizar', 'trabalhar', 'organizar',
      'descobrir', 'aventurar', 'descrever', 'acariciar', 'colaborar', 'comemorar', 'agradecer', 'sussurrar',
      'abrasador', 'empolgado', 'grosseiro', 'desonesto', 'confiável', 'brilhante', 'reluzente', 'tranquilo',
      'fedorento', 'perfumado', 'reservado', 'universal', 'relevante', 'coelhinho', 'palhinhas', 'companhia',
      'missionar', 'passional', 'processar', 'xintoísta', 'expressar', 'bicharada', 'marchinha', 'flechinha',
      'chicotada', 'embaixada', 'empacotar', 'impulsivo', 'imponente', 'ambicioso', 'ambiência', 'amplitude',
      'dezesseis', 'cinquenta', 'raramente', 'fevereiro', 'miligrama', 'mililitro', 'decilitro', 'esmeralda',
      'helicoide', 'organismo', 'longitude', 'gravidade', 'meteorito', 'anticorpo', 'liberdade', 'sabedoria',
      'progresso', 'malmequer', 'cachalote', 'temperado', 'congelado', 'cobertura', 'vinagrete', 'sobremesa',
      'digestivo', 'casamento', 'padrinhos', 'madrinhas', 'religioso', 'quadrilha', 'papai-noel', 'Réveillon',
      'quociente', 'dividendo', 'resultado', 'algarismo', 'numerador', 'imprópria', 'predicado', 'provérbio',
      'injuntiva', 'eufemismo', 'coerência', 'quadrinha', 'monarquia', 'indústria', 'imperador', 'cavaleiro',
      'humanismo', 'burguesia', 'sindicato', 'comunismo', 'cidadania', 'meridiano', 'densidade', 'desacordo',
      'bilateral', 'bissexual', 'semifinal', 'estrutura', 'estudante', 'baterista', 'alpinismo', 'caldeirão',
      'outrossim', 'quer dizer', 'com efeito', 'na verdade', 'entendido', 'impreciso', 'permitido', 'caderneta',
      'porcelana', 'chiqueiro', 'scooby-doo', 'caratinga', 'flor-de-lis', 'discordar', 'autorizar', 'engrossar',
      'aproximar', 'comunicar', 'notificar', 'sinalizar', 'codificar', 'vagamente', 'diferente', 'tamarindo',
      'sapodilla', 'tae-kwon-do', 'filtragem', 'taxonomia', 'dominante', 'ontologia', 'axiologia', 'empirismo',
      'idealismo', 'silogismo',
      ],
      dificil: [
      'aguapé', 'erosão', 'edição', 'missão', 'emoção', 'ilusão', 'evasão', 'amanhã',
      'ângulo', 'adição', 'oração', 'até que', 'salamandra', 'pernilongo', 'clementina', 'alcachofra',
      'brigadeiro', 'cappuccino', 'enfermeiro', 'enfermeira', 'marceneiro', 'jardineiro', 'agricultor', 'jornalista',
      'presidente', 'governador', 'embaixador', 'entregador', 'ilustrador', 'computador', 'biblioteca', 'secretaria',
      'ortografia', 'campeonato', 'orientador', 'supervisor', 'merendeiro', 'sociologia', 'caligrafia', 'tecnologia',
      'trepadeira', 'laranjeira', 'amendoeira', 'tempestade', 'entardecer', 'lavanderia', 'prateleira', 'detergente',
      'micro-ondas', 'frigideira', 'pimenteiro', 'cristalino', 'estrabismo', 'comprimido', 'tomografia', 'tratamento',
      'jardineira', 'plataforma', 'loteamento', 'sorveteria', 'lanchonete', 'prefeitura', 'cruzamento', 'pentagrama',
      'fotografia', 'quadrinhos', 'tipografia', 'smartphone', 'artificial', 'entusiasmo', 'melancolia', 'nervosismo',
      'apresentar', 'participar', 'homenagear', 'encantador', 'resistente', 'congelante', 'encharcado', 'negligente',
      'silencioso', 'particular', 'importante', 'verdadeiro', 'incompleto', 'xingamento', 'enchimento', 'caprichoso',
      'simpatizar', 'quinhentos', 'centilitro', 'hectolitro', 'fahrenheit', 'horizontal', 'Pernambuco', 'Tiradentes',
      'nordestino', 'paulistano', 'magnetismo', 'sofrimento', 'influência', 'mastodonte', 'baleia-azul', 'rendimento',
      'marchinhas', 'serpentina', 'Dia-dos-Pais', 'pictograma', 'democracia', 'hieroglifo', 'cuneiforme', 'socialismo',
      'tombamento', 'continente', 'reescrever', 'microclima', 'microbiota', 'macrocosmo', 'tricampeão', 'trilateral',
      'fazendeiro', 'misterioso', 'violinista', 'esportista', 'brasileiro', 'lentamente', 'finalmente', 'geralmente',
      'certamente', 'claramente', 'entretanto', 'por mais que', 'por exemplo', 'complicado', 'calligraph', 'pernalonga',
      'zamioculca', 'desenrolar', 'sintetizar', 'amplamente', 'fortemente', 'fracamente', 'densamente', 'totalmente',
      'localmente', 'hierarquia', 'manga-tommy', 'kick-boxing', 'tiro-ao-alvo', 'mutualismo', 'herbivoria', 'carnivoria',
      'decomposto', 'citoplasma', 'fluxograma', 'pêssego', 'abóbora', 'orégano', 'químico', 'redação',
      'colação', 'química', 'epífita', 'erupção', 'estação', 'córrego', 'igarapé', 'aquário',
      'terraço', 'pescoço', 'coração', 'músculo', 'biquíni', 'máscara', 'açougue', 'natação',
      'coleção', 'aversão', 'apático', 'escasso', 'pressão', 'comoção', 'direção', 'redução',
      'solução', 'votação', 'eleição', 'seleção', 'injeção', 'decisão', 'invasão', 'revisão',
      'divisão', 'escolha', 'pássaro', 'gressão', 'excesso', 'ambição', 'ambíguo', 'acarajé',
      'guaraná', 'onívoro', 'líquido', 'mutação', 'lúgubre', 'máquina', 'vírgula', 'atenção',
      'manhanã', 'pão-de-ló', 'chá-mate', 'oblíquo', 'locução', 'anáfora', 'bússola', 'até-mais',
      'que-pena', 'cão-lobo', 'isótopo', 'análise', 'dedução', 'indução', 'abdução', 'carpinteiro',
      'confeiteiro', 'comerciante', 'historiador', 'coordenador', 'programador', 'gimnosperma', 'angiosperma', 'autoestrada',
      'confeitaria', 'restaurante', 'brincadeira', 'contrabaixo', 'performance', 'desenvolver', 'malcheiroso', 'comprimento',
      'empreiteiro', 'impulsionar', 'implementar', 'comprometer', 'Centro-Oeste', 'patriotismo', 'platelminto', 'ingrediente',
      'suplementar', 'substantivo', 'dramaturgia', 'cartografia', 'coordenadas', 'hidrografia', 'deslealdade', 'reorganizar',
      'tristemente', 'normalmente', 'concordamos', 'sansevieria', 'multiplicar', 'interpretar', 'globalmente', 'surf-de-ondas',
      'sertanistas', 'tropeirismo', 'cloroplasto', 'confluência', 'pragmatismo', 'contraprova', 'antílope', 'preguiça',
      'ariranha', 'mexilhão', 'libélula', 'maracujá', 'escarola', 'cogumelo', 'macarrão', 'tataravô',
      'afilhado', 'afilhada', 'mecânico', 'filósofo', 'elástico', 'aquarela', 'capítulo', 'robótica',
      'orquídea', 'pôr-do-sol', 'arco-íris', 'caçarola', 'espátula', 'amígdala', 'estômago', 'vesícula',
      'hipófise', 'agasalho', 'caminhão', 'elétrico', 'semáforo', 'passagem', 'lotérica', 'depósito',
      'basílica', 'críquete', 'escalada', 'atabaque', 'reco-reco', 'acrílica', 'pichação', 'placa-mãe',
      'satélite', 'autônomo', 'diversão', 'rejeição', 'decepção', 'incômodo', 'confusão', 'escolher',
      'arrumado', 'inseguro', 'possível', 'avançado', 'promoção', 'formação', 'produção', 'tradução',
      'proteção', 'expansão', 'extensão', 'dimensão', 'inclusão', 'previsão', 'sensação', 'invenção',
      'linhagem', 'penhasco', 'arrecife', 'terrível', 'assumido', 'embaraço', 'olímpico', 'hexágono',
      'octógono', 'eneágono', 'decágono', 'polígono', 'pirâmide', 'anguloso', 'Maranhão', 'São-Paulo',
      'indígena', 'nutrição', 'extinção', 'alumínio', 'oxigênio', 'potássio', 'molécula', 'condução',
      'refração', 'difração', 'absorção', 'vibração', 'genética', 'escassez', 'tradição', 'bate-boca',
      'curimatã', 'anelídeo', 'variação', 'escaleno', 'metáfora', 'catáfora', 'figurado', 'monólogo',
      'migração', 'projeção', 'pré-natal', 'bilíngue', 'foguetão', 'rascunho', 'cerâmica', 'terrário',
      'estábulo', 'barragem', 'tucunaré', 'que-legal', 'que-irado', 'que-falta', 'aeróbica', 'predação',
      'retículo', 'fenótipo', 'genótipo', 'hipótese', 'antítese', 'transferidor', 'empreendedor', 'simplesmente',
      'complementar', 'compreendido', 'parcialmente', 'bandeirantes', 'periquito', 'andorinha', 'gafanhoto', 'escorpião',
      'beterraba', 'abobrinha', 'cebolinha', 'arquiteto', 'arquiteta', 'garçonete', 'psicólogo', 'psicóloga',
      'sociólogo', 'fotógrafo', 'dançarino', 'astrônomo', 'canetinha', 'auditório', 'gramática', 'pontuação',
      'parágrafo', 'conclusão', 'seminário', 'olimpíada', 'português', 'recreação', 'culinária', 'helicônia',
      'araucária', 'jacarandá', 'relâmpago', 'aguaceiro', 'enxurrada', 'terremoto', 'amanhecer', 'zoológico',
      'luminária', 'lavatório', 'assadeira', 'mandíbula', 'antebraço', 'meia-calça', 'sapatilha', 'maletinha',
      'automóvel', 'dirigível', 'para-brisa', 'rotatória', 'alfândega', 'município', 'metrópole', 'capelinha',
      'cemitério', 'arremesso', 'ginástica', 'luta-livre', 'palitinho', 'cabra-cega', 'escultura', 'passarela',
      'antivírus', 'esperança', 'interesse', 'apressado', 'esforçado', 'ordinário', 'aveludado', 'espinhoso',
      'incorreto', 'instrução', 'pretensão', 'apreensão', 'suspensão', 'persuasão', 'maravilha', 'arrebatar',
      'arrematar', 'arrecadar', 'assediado', 'exercício', 'excelente', 'exagerado', 'exclusivo', 'churrasco',
      'embalagem', 'embaraçar', 'ampliação', 'simpático', 'dezessete', 'milímetro', 'decímetro', 'azul-royal',
      'triângulo', 'pentágono', 'heptágono', 'simétrico', 'irregular', 'República', 'herbívoro', 'carnívoro',
      'convecção', 'flutuação', 'via-láctea', 'esqueleto', 'prevenção', 'injustiça', 'igualdade', 'benefício',
      'linguagem', 'inimizade', 'mão-de-obra', 'arara-azul', 'bolo-de-mel', 'requeijão', 'vitamina-c', 'guarda-sol',
      'tira-teima', 'amolecido', 'guacamole', 'aperitivo', 'bem-casado', 'cerimônia', 'subtração', 'diferença',
      'recíproco', 'milésimos', 'proporção', 'perímetro', 'favorável', 'conjunção', 'narrativa', 'hipérbole',
      'sinonímia', 'antonímia', 'homonímia', 'paronímia', 'hiponímia', 'maiúscula', 'adivinhas', 'neolítico',
      'aqueducto', 'recomeçar', 'antiácido', 'binóculos', 'carinhoso', 'carinhosa', 'batidinha', 'uma vez que',
      'em síntese', 'de que modo', 'giz-de-cera', 'plantação', 'rodovalho', 'calêndula', 'assegurar', 'centésimo',
      'terranova', 'manga-rosa', 'saprófita', 'autótrofo', 'ribossomo', 'recessivo', 'argumento', 'evidência',
      'passarinho', 'dromedário', 'caranguejo', 'jabuticaba', 'hambúrguer', 'manjericão', 'professora', 'engenheiro',
      'engenheira', 'cozinheiro', 'empresário', 'economista', 'secretário', 'secretária', 'assistente', 'marinheiro',
      'socorrista', 'salva-vidas', 'giz-de-lousa', 'impressora', 'dicionário', 'termômetro', 'refeitório', 'literatura',
      'abacateiro', 'crisântemo', 'patrimônio', 'cobre-leito', 'criado-mudo', 'calendário', 'borrifador', 'centrífuga',
      'torradeira', 'cartilagem', 'leucócitos', 'amigdalite', 'tensímetro', 'ambulância', 'enxaguante', 'necessaire',
      'monotrilho', 'acelerador', 'carregador', 'passaporte', 'rodoviária', 'bilheteria', 'condomínio', 'ministério',
      'apart-hotel', 'lançamento', 'pular-corda', 'figurinhas', 'tropicália', 'folclórica', 'banda-larga', 'aplicativo',
      'felicidade', 'gargalhada', 'serenidade', 'frustração', 'descoberta', 'fidelidade', 'tolerância', 'configurar',
      'atravessar', 'amadurecer', 'ressequido', 'organizado', 'desanimado', 'apimentado', 'barulhento', 'estressado',
      'construção', 'meravilhar', 'espinheiro', 'borbolinha', 'passatempo', 'classifica', 'empréstimo', 'cambalhota',
      'olimpíadas', 'centímetro', 'hectômetro', 'quilograma', 'velocidade', 'verde-oliva', 'branco-gelo', 'reciclagem',
      'hidrogênio', 'nitrogênio', 'frequência', 'isolamento', 'quarentena', 'ignorância', 'retrocesso', 'abundância',
      'autoridade', 'humanidade', 'porta-malas', 'gavião-real', 'sempre-viva', 'sexta-feira', 'caixa-forte', 'cofre-forte',
      'porta-jóias', 'capuchinho', 'assombrado', 'Dia-das-Mães', 'Dia-do-Amigo', 'irracional', 'centésimos', 'capacidade',
      'personagem', 'descritiva', 'expositiva', 'polissemia', 'inferência', 'estribilho', 'artesanato', 'astrolábio',
      'hemisfério', 'descuidado', 'reconhecer', 'pré-history', 'automotivo', 'multimídia', 'salgadinho', 'cervejinha',
      'caipirinha', 'igualmente', 'que espécie', 'de que forma', 'exatamente', 'fantástico', 'trabalhoso', 'emergência',
      'autorizado', 'galinheiro', 'pato-donald', 'cavaquinha', 'rivalidade', 'acrescenta', 'indefinido', 'feliz-natal',
      'pobrezinho', 'manga-haden', 'comunidade', 'cromossomo', 'homozigoto', 'até-logo', 'rinoceronte', 'orangotango',
      'companheiro', 'responsável', 'eletricista', 'mototaxista', 'calculadora', 'aprendizado', 'certificado', 'pessegueiro',
      'castanheira', 'cordilheira', 'sala-de-estar', 'travesseiro', 'saboneteira', 'processador', 'sobrancelha', 'panturrilha',
      'medicamento', 'diagnóstico', 'desodorante', 'impermeável', 'suspensório', 'rasteirinha', 'porta-moedas', 'motocicleta',
      'quadriciclo', 'porta-aviões', 'combustível', 'desembarque', 'borracharia', 'acampamento', 'montanhismo', 'privacidade',
      'impaciência', 'desconforto', 'curiosidade', 'resiliência', 'honestidade', 'integridade', 'compreensão', 'parabenizar',
      'desaparecer', 'determinado', 'inteligente', 'espirituoso', 'trabalhador', 'empalidecer', 'compromisso', 'trombadinha',
      'porcentagem', 'Minas-Gerais', 'Rio-Amazonas', 'bumba-meu-boi', 'crescimento', 'temperatura', 'resistência', 'permanência',
      'desvantagem', 'ensinamento', 'modernidade', 'peixe-espada', 'painel-solar', 'celenterado', 'desidratado', 'chimichurri',
      'salgadinhos', 'travessuras', 'denominador', 'percentagem', 'onomatopeia', 'agricultura', 'capitalismo', 'liberalismo',
      'arqueologia', 'descontente', 'redescobrir', 'superlativo', 'intercâmbio', 'multitarefa', 'guitarrista', 'cachorrinho',
      'estrelinhas', 'rapidamente', 'alegremente', 'por menos que', 'do mesmo modo', 'antes de tudo', 'ao contrário', 'desde quando',
      'felicidades', 'discordamos', 'espetacular', 'dispensável', 'mickey-mouse', 'peacock-bass', 'decodificar', 'nitidamente',
      'diversidade', 'pluralidade', 'quadruplica', 'quintuplica', 'manga-palmer', 'manga-espada', 'salto-triplo', 'ciclo-do-ouro',
      'parasitismo', 'amensalismo', 'mitocôndria', 'prognóstico', 'metodologia', 'positivismo', 'experimento', 'educação',
      'narração', 'excursão', 'cerração', 'animação', 'agitação', 'evolução', 'ascensão', 'exclusão',
      'inovação', 'recessão', 'azul-bebê', 'operação', 'abolição', 'elevação', 'arregaça', 'aquífero',
      'execução', 'refrigerante', 'deslizamento', 'revestimento', 'porta-shampoo', 'astigmatismo', 'retrovisores', 'supermercado',
      'hipermercado', 'hamburgueria', 'motociclismo', 'semicondutor', 'redes-sociais', 'cumplicidade', 'encantamento', 'persistência',
      'simplicidade', 'compartilhar', 'comprometido', 'extrovertido', 'criatividade', 'rebaixamento', 'amplificador', 'quatrocentos',
      'Rio-Tocantins', 'decompositor', 'profundidade', 'encadeamento', 'concordância', 'proletariado', 'antropologia', 'sinceramente',
      'ao mesmo tempo', 'enquanto isso', 'inversamente', 'quantas vezes', 'esparsamente', 'precisamente', 'fraternidade', 'continuidade',
      'maior-ou-igual', 'mountain-bike', 'comensalismo', 'detritivoria', 'nomenclatura', 'planejamento', 'racionalismo', 'materialismo',
      'pré-escola', 'descrição', 'aprovação', 'exposição', 'jequitibá', 'inundação', 'equinócio', 'depressão',
      'acessório', 'emigração', 'imigração', 'patinação', 'bossa-nova', 'televisão', 'segurança', 'admiração',
      'superação', 'minúsculo', 'bagunçado', 'aromático', 'locomoção', 'revolução', 'percussão', 'decoração',
      'dedicação', 'aplicação', 'motivação', 'profissão', 'excessivo', 'retângulo', 'Rio-Paraná', 'adaptação',
      'obrigação', 'expressão', 'acessível', 'arroz-doce', 'saca-rolha', 'isósceles', 'denotação', 'conotação',
      'minúscula', 'vegetação', 'mineração', 'interação', 'semi-árido', 'amazônico', 'além disso', 'até quando',
      'involução', 'regressão', 'que-bacana', 'cão-de-água', 'guanábana', 'população', 'avaliação', 'refutação',
      'validação', 'nutricionista', 'recepcionista', 'churrasqueira', 'hipermetropia', 'condicionador', 'entroncamento', 'contentamento',
      'internacional', 'churrasquinho', 'pertencimento', 'nematelmintos', 'perpendicular', 'autobiografia', 'macro-ambiente', 'macroeconomia',
      'especialmente', 'provavelmente', 'profundamente', 'primeiramente', 'eventualmente', 'estreitamente', 'variavelmente', 'continuamente',
      'completamente', 'integralmente', 'regionalmente', 'hipopótamo', 'batata-doce', 'grão-de-bico', 'noz-moscada', 'matemático',
      'arqueólogo', 'lápis-de-cor', 'paquímetro', 'acentuação', 'introdução', 'reprovação', 'matemática', 'xique-xique',
      'amanhecida', 'crepúsculo', 'escritório', 'home-cinema', 'escorredor', 'açucareiro', 'internação', 'teleférico',
      'para-choque', 'repartição', 'eletrônica', 'instalação', 'ilustração', 'satisfação', 'empolgação', 'realização',
      'arrogância', 'tomar-banho', 'mal-educado', 'preguiçoso', 'energético', 'impossível', 'informação', 'observação',
      'exploração', 'atribuição', 'preparação', 'legislação', 'inspiração', 'vizinhança', 'território', 'necessário',
      'assinatura', 'combinação', 'quilômetro', 'rosa-choque', 'verde-limão', 'preto-fosco', 'Mato-Grosso', 'Serra-do-Mar',
      'Serra-Geral', 'respiração', 'reprodução', 'gás-natural', 'sublimação', 'circulação', 'estagnação', 'boca-de-siri',
      'gato-do-mato', 'terça-feira', 'avião-a-jato', 'celebração', 'preposição', 'comparação', 'assonância', 'progressão',
      'manutenção', 'escravidão', 'conurbação', 'super-herói', 'auto-escola', 'lírio-da-paz', 'cooperação', 'competição',
      'equilíbrio', 'integração', 'segregação', 'diminuição', 'com-licença', 'desculpe-me', 'que-maneiro', 'espetáculo',
      'que-saudade', 'putrefação', 'mensuração', 'empreendimento', 'constantemente', 'macroestrutura', 'macronutriente', 'multifuncional',
      'principalmente', 'posteriormente', 'batata-baroa', 'adolescente', 'veterinário', 'veterinária', 'antropólogo', 'microscópio',
      'laboratório', 'aula-passeio', 'informática', 'pteridófita', 'nascer-do-sol', 'sala-de-jogos', 'guarda-roupa', 'colher-de-pau',
      'constipação', 'antibiótico', 'ressonância', 'guarda-chuva', 'caminhonete', 'micro-ônibus', 'helicóptero', 'escavadeira',
      'ambulatório', 'pega-varetas', 'amarelinhas', 'arte-digital', 'alto-falante', 'preocupação', 'introversão', 'extroversão',
      'espreguiçar', 'acompanhado', 'instituição', 'maravilhoso', 'arredondado', 'arrebentado', 'necessidade', 'assassinato',
      'missionário', 'implantação', 'azul-celeste', 'amarelo-ouro', 'festa-junina', 'caldo-de-cana', 'ecossistema', 'preservação',
      'condensação', 'transmissão', 'corpo-humano', 'musculatura', 'antiguidade', 'dente-de-leão', 'doce-de-leite', 'queijo-minas',
      'suco-de-fruta', 'quarta-feira', 'quinta-feira', 'lula-gigante', 'modo-de-fazer', 'molho-branco', 'aniversário', 'regra-de-três',
      'interjeição', 'pré-história', 'paleolítico', 'restauração', 'supersônico', 'multilíngue', 'semicírculo', 'para começar',
      'em oposição a', 'em que medida', 'obrigatório', 'conservação', 'que-incrível', 'são-bernardo', 'figo-da-índia', 'banana-prata',
      'tiro-com-arco', 'escravatura', 'proclamação', 'fermentação', 'heterótrofo', 'confirmação', 'infográfico', 'ornitorrinco',
      'estrela-do-mar', 'fruta-do-conde', 'achocolatado', 'farmacêutico', 'paleontólogo', 'caminhoneiro', 'enciclopédia', 'amor-perfeito',
      'aurora-boreal', 'nuvem-de-chuva', 'sala-de-jantar', 'mesa-de-centro', 'porta-retrato', 'pasta-de-dente', 'empilhadeira', 'universidade',
      'churrascaria', 'pingue-pongue', 'documentário', 'inteligência', 'intolerância', 'generosidade', 'misericórdia', 'distribuição',
      'contribuição', 'constituição', 'pequenininho', 'terrificante', 'Rio-de-Janeiro', 'eletricidade', 'sistema-solar', 'sistema-imune',
      'desigualdade', 'oportunidade', 'consequência', 'conhecimento', 'porco-espinho', 'pombo-correio', 'esponja-do-mar', 'substituição',
      'creme-de-leite', 'caldo-de-carne', 'desfavorável', 'cidade-estado', 'renascimento', 'antialérgico', 'bicentenário', 'nesse ínterim',
      'de que maneira', 'boa-madrugada', 'interessante', 'reservatório', 'hidrelétrica', 'termelétrica', 'obscuramente', 'borrosamente',
      'regularmente', 'erroneamente', 'corretamente', 'estabilidade', 'uniformidade', 'fragmentação', 'menor-ou-igual', 'salto-com-vara',
      'arrendamento', 'heterozigoto', 'olho-d-água', 'equitação', 'excitação', 'irritação', 'discussão', 'figuração',
      'fonoaudiólogo', 'bibliotecário', 'protetor-solar', 'colheitadeira', 'automobilismo', 'contemporâneo', 'tranquilidade', 'solidariedade',
      'sociabilidade', 'transformação', 'multicolorido', 'Independência', 'desonestidade', 'baleia-jubarte', 'caldo-de-frango', 'paralelogramo',
      'probabilidade', 'União-Europeia', 'desorganizado', 'superpotência', 'autoconfiança', 'intermediário', 'semifinalista', 'brigadeirinho',
      'absolutamente', 'paralelamente', 'pelo contrário', 'possivelmente', 'imediatamente', 'uniformemente', 'genericamente', 'acertadamente',
      'oportunamente', 'instabilidade', 'verticalidade', 'salto-em-altura', 'inconfidência', 'fotoautótrofo', 'rosa-dos-ventos', 'monitoramento',
      'epistemologia', 'fenomenologia', 'imunização', 'associação', 'fascinação', 'imaginação', 'arranha-céu', 'evaporação',
      'irradiação', 'aceleração', 'equilátero', 'acutângulo', 'aliteração', 'inquisição', 'caixa-d-água', 'bambu-mossô',
      'unificação', 'não-há-de-quê', 'açaí-do-pará', 'banana-maçã', 'otimização', 'fisioterapeuta', 'meteorologista', 'estacionamento',
      'transatlântico', 'companheirismo', 'desapontamento', 'insignificante', 'percussionista', 'extraordinário', 'frequentemente', 'Rio-Grande-do-Sul',
      'biodiversidade', 'vale-transporte', 'prato-principal', 'Dia-das-Crianças', 'circunferência', 'descobrimentos', 'tranquilamente', 'com que objetivo',
      'por quanto tempo', 'universalmente', 'Princesa-Isabel', 'escalímetro', 'dissertação', 'recuperação', 'arquipélago', 'articulação',
      'dor-de-cabeça', 'óculos-de-sol', 'semi-reboque', 'sinalização', 'tênis-de-mesa', 'comunicação', 'colaboração', 'repercussão',
      'azul-marinho', 'assimétrico', 'civilização', 'olho-de-peixe', 'cão-de-guarda', 'leão-marinho', 'pão-de-queijo', 'metrô-linhas',
      'camarão-rosa', 'pré-aquecido', 'comemoração', 'verificação', 'obtusângulo', 'trava-língua', 'colonização', 'urbanização',
      'até que ponto', 'feliz-páscoa', 'banana-terra', 'Vasco-da-Gama', 'fuso-horário', 'organização', 'atualização', 'Planalto-Central',
      'desenvolvimento', 'cadeia-alimentar', 'verdadeiramente', 'em primeiro lugar', 'simultaneamente', 'por quantas vezes', 'descriptografar', 'permanentemente',
      'temporariamente', 'fracionadamente', 'particularmente', 'apresentação', 'vitória-régia', 'escrivaninha', 'dor-de-barriga', 'estetoscópio',
      'cabo-de-guerra', 'determinação', 'justificação', 'manifestação', 'participação', 'fotossíntese', 'reutilização', 'ervilha-torta',
      'pato-selvagem', 'tucano-de-bico', 'café-com-leite', 'segunda-feira', 'vara-de-pescar', 'rádio-relógio', 'macaco-aranha', 'camarão-cinza',
      'globalização', 'antisséptico', 'coraçãozinho', 'padronização', 'customização', 'feliz-ano-novo', 'pastor-alemão', 'banana-nanica',
      'decomposição', 'círculo-polar', 'linha-do-tempo', 'curva-de-nível', 'estruturação', 'desflorestamento', 'reaproveitamento', 'em outras palavras',
      'superficialmente', 'convenientemente', 'sala-de-leitura', 'pronto-socorro', 'desorientação', 'desnecessário', 'representação', 'administração',
      'implementação', 'possibilidade', 'metro-quadrado', 'monocromático', 'Santa-Catarina', 'Mata-Atlântica', 'originalidade', 'ferro-de-passar',
      'boto-cor-de-rosa', 'tubarão-branco', 'tubarão-baleia', 'molho-vermelho', 'multiplicação', 'argumentativa', 'referenciação', 'irresponsável',
      'desequilíbrio', 'pré-vestibular', 'pré-operatório', 'há quanto tempo', 'rosa-do-deserto', 'adequadamente', 'singularidade', 'centralização',
      'ciclo-do-açúcar', 'pimenta-do-reino', 'liquidificador', 'esconde-esconde', 'reconhecimento', 'arrependimento', 'maravilhamento', 'vermelho-sangue',
      'sistema-nervoso', 'coelho-da-índias', 'feijão-tropeiro', 'ar-condicionado', 'tempo-de-preparo', 'acompanhamento', 'arredondamento', 'espaço-amostral',
      'em que condições', 'cachorro-quente', 'solha-das-pedras', 'irregularmente', 'incorretamente', 'fila-brasileiro', 'marcha-atlética', 'lençol-freático',
      'pé-de-moleque', 'pé-de-galinha', 'seguro-saúde', 'café-da-manhã', 'ovo-de-páscoa', 'adivinhação', 'cortador-de-unhas', 'porta-documentos',
      'correspondência', 'Distrito-Federal', 'hereditariedade', 'leite-condensado', 'Dia-dos-Namorados', 'direitos-humanos', 'autossuficiente', 'violeta-africana',
      'especificamente', 'descontinuidade', 'horizontalidade', 'ciclismo-de-pista', 'quimioautótrofo', 'argumentação', 'quebra-cabeça', 'qualificação',
      'esqueça-me-não', 'orelha-de-gato', 'maracujá-roxo', 'maracujá-doce', 'polo-aquático', 'retroescavadeira', 'responsabilidade', 'Rio-Grande-do-Norte',
      'sustentabilidade', 'lista-de-presentes', 'interdisciplinar', 'semiprofissional', 'subsequentemente', 'indubitavelmente', 'brinco-de-princesa', 'salto-em-distância',
      'ciclo-do-pau-brasil', 'área-de-serviço', 'vaso-sanitário', 'tábua-de-passar', 'escova-de-dente', 'classificação', 'identificação', 'Espírito-Santo',
      'solidificação', 'cavalo-marinho', 'carro-elétrico', 'molho-de-tomate', 'em que situação', 'desaceleração', 'banana-da-terra', 'esqui-aquático',
      'quantificação', 'categorização', 'intermitentemente', 'ciclismo-de-estrada', 'data-internacional', 'desertificação', 'desenho-animado', 'prestar-atenção',
      'paralelepípedo', 'energia-térmica', 'campo-magnético', 'aquecedor-solar', 'caldo-de-legumes', 'personificação', 'placa-tectônica', 'metropolização',
      'personalização', 'terraço-fluvial', 'divisor-de-águas', 'sistematização', 'palmeira-de-interior', 'inconvenientemente', 'espreguiçadeira', 'posto-de-gasolina',
      'laranja-queimado', 'Mato-Grosso-do-Sul', 'Oceano-Atlântico', 'Rio-São-Francisco', 'beija-me-depressa', 'chocolate-quente', 'cartão-de-crédito', 'leopardo-marinho',
      'lagosta-do-caribe', 'com que propósito', 'inadequadamente', 'luta-greco-romana', 'ciclo-da-borracha', 'trópico-de-câncer', 'porta-guardanapos', 'sistema-endócrino',
      'elefante-africano', 'industrialização', 'anti-inflamatório', 'com que finalidade', 'nado-sincronizado', 'célula-eucarionte', 'horário-universal', 'escala-gráfica',
      'educação-física', 'área-de-proteção', 'máquina-de-lavar', 'regulamentação', 'guaraná-natural', 'ônibus-expresso', 'despertador-digital', 'durante quanto tempo',
      'vale-alimentação', 'maracujá-amarelo', 'maracujá-gigante', 'em que circunstâncias', 'tapete-de-banheiro', 'futebol-americano', 'elefante-asiático', 'espada-de-são-jorge',
      'descentralização', 'feliz-aniversário', 'mergulho-olímpico', 'nado-de-velocidade', 'ginástica-rítmica', 'centro-comunitário', 'bicicleta-elétrica', 'caranguejo-eremita',
      'lançamento-de-dardo', 'luta-livre-olímpica', 'respiração-celular', 'célula-procarionte', 'escala-numérica', 'gorila-das-planícies', 'ginástica-artística', 'levantamento-de-peso',
      'manteiga-clarificada', 'corrida-com-barreiras', 'maratona-aquática', 'lançamento-de-disco', 'caneta-hidrográfica', 'quilômetro-quadrado', 'ciclo-biogeoquímico', 'lançamento-de-martelo',
      'ginástica-de-trampolim', 'trópico-de-capricórnio', 'corrida-de-revezamento', 'golfinho-nariz-de-garrafa',
      ],
    };
  }

  /**
   * Retorna palavras embaralhadas e únicas para a sessão.
   * @param {number} count - Quantidade de palavras
   * @param {'facil'|'medio'|'dificil'} nivel - Nível de dificuldade
   * @returns {Word[]}
   */
  createSessionWords(count, nivel = 'facil') {
    const bank   = this._banks[nivel] || this._banks['facil'];
    const shuffled = this._shuffle([...bank]);
    const selected = shuffled.slice(0, Math.min(count, shuffled.length));
    return selected.map(text => new Word(text));
  }

  /** Quantidade de palavras disponíveis por nível */
  bankSize(nivel) {
    return (this._banks[nivel] || []).length;
  }

  /** Embaralha array in-place — Fisher-Yates */
  _shuffle(arr) {
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
  }
}
